/* Comando para coletar os Dados de Estatísticas no ISQL

-- COLETA ESTATISTICA DA ORIGEM (Coletar no momento do Setup)
"c:\Program Files\Firebird\Firebird_3_0\isql.exe" 
	-user SYSDBA 
	-password masterkey
	-output ESTATISTICAS_ORIGEM.LOG 
	-input Z:\DEV\MODELO\DADOS_ESTATISTICAS.SQL
	"C:\TEMP\DADOS_ORIGEM.FDB" 
	
-- COLETA ESTATISTICA DA DESTINO (Coletar no momento da Publicação)
"c:\Program Files\Firebird\Firebird_3_0\isql.exe" 
	-user SYSDBA 
	-password masterkey
	-output ESTATISTICAS_DESTINO.LOG 
	-input Z:\DEV\MODELO\DADOS_ESTATISTICAS.SQL
	"C:\TEMP\DADOS_DESTINO.FDB" 
*/

/* SQL que coleta os dados de uma base FuturaFuturaSistemas */
SET TERM #;
---------- BLOCO INICIO ----------
EXECUTE BLOCK
RETURNS (
	IMPORTACAO INT,
	INPUT_OUTPUT VARCHAR(1),
    CADASTRO INT,
    CLIENTE INT,
    FORNECEDOR INT,
    TRANSPORTADORA INT,
    PRODUTO INT,
    TOTAL INT,
    --CODBAR INT,
    ESTOQUE VARCHAR(80)
)
AS 
    DECLARE IMPORTACAO_ID INT = 8362;
    DECLARE INP_OUT VARCHAR(1) = 'O';
    DECLARE EMPRESA_ID INT = 1;
    DECLARE ID INT = 0;
    DECLARE ESTOQUE_TOTAL FLOAT = 0;
    DECLARE ESTOQUE_VALOR FLOAT = 0;
BEGIN
	IMPORTACAO = :IMPORTACAO_ID;
	INPUT_OUTPUT = :INP_OUT;
    SELECT COUNT(*) FROM CADASTRO c WHERE c.ID > 15 INTO :CADASTRO;
    SELECT COUNT(*) FROM CADASTRO c WHERE c.CHK_CLIENTE = 'S' AND c.ID > 15 INTO :CLIENTE;
    SELECT COUNT(*) FROM CADASTRO c WHERE c.CHK_FORNECEDOR = 'S' AND c.ID > 15 INTO :FORNECEDOR;
    SELECT COUNT(*) FROM CADASTRO c WHERE c.CHK_TRANSPORTADORA = 'S' AND c.ID > 15 INTO :TRANSPORTADORA;
    SELECT COUNT(*) FROM PRODUTO INTO :PRODUTO;
    TOTAL = :CADASTRO + :PRODUTO;
    --SELECT COUNT(*) FROM PRODUTO_CODIGO_BARRA INTO :CODBAR;
    FOR SELECT ID FROM PRODUTO INTO :ID DO
        BEGIN
            SELECT SALDO FROM SP_GET_PRODUTO_SALDO(:EMPRESA_ID, :ID) INTO :ESTOQUE_VALOR;
            ESTOQUE_TOTAL = :ESTOQUE_TOTAL + :ESTOQUE_VALOR;
        END
        
    ESTOQUE = REPLACE(CAST(:ESTOQUE_TOTAL AS VARCHAR(80)), '.', ',');
    
    SUSPEND;
END#
---------- BLOCO FIM ----------
SET TERM ;#