SET TERM #;

EXECUTE BLOCK
RETURNS (
    ID      INT,
	IO		VARCHAR(1),
    CAD     INT,
    CLI     INT,
    FORN    INT,
    TRANS   INT,
    PROD    INT,
    TOTAL   INT,
    EST     VARCHAR(80)
)
AS
    DECLARE VARIABLE ID_IMP INT = 9820;
	DECLARE VARIABLE I_O VARCHAR(1) = 'I';
    DECLARE VARIABLE ID_EMP INT = 1;
    DECLARE VARIABLE ID_EST INT = 0;
    DECLARE VARIABLE TOTAL_EST FLOAT = 0;
    DECLARE VARIABLE VALOR_EST FLOAT = 0;
BEGIN
    ID = :ID_IMP;
	IO = :I_O;
    SELECT COUNT(*) FROM VW_CLIENTE c           WHERE c.RAZAO_SOCIAL <> ''  INTO :CLI;
    SELECT COUNT(*) FROM VW_FORNECEDOR f        WHERE f.RAZAO_SOCIAL <> ''  INTO :FORN;
    SELECT COUNT(*) FROM VW_TRANSPORTADORA t    WHERE t.RAZAO_SOCIAL <> ''  INTO :TRANS;
    SELECT COUNT(*) FROM VW_PRODUTO p	INTO :PROD;
    CAD = :CLI + :FORN + :TRANS;
    TOTAL = :CAD + :PROD;
    
    EST = REPLACE(CAST((SELECT COALESCE(SUM(e.ESTOQUE_ATUAL), 0) FROM VW_ESTOQUE e WHERE e.ESTOQUE_ATUAL <> 0) AS VARCHAR(80)), '.', ',');

    SUSPEND;
END#

SET TERM ;#

