USE [Hiper];
GO
BEGIN TRANSACTION;
GO
BEGIN
	SELECT 
		'8288' 											AS ID
		,(SELECT COUNT(*) FROM dbo.VW_CLIENTE) +
		(SELECT COUNT(*) FROM dbo.VW_FORNECEDOR) +
		(SELECT COUNT(*) FROM dbo.VW_TRANSPORTADORA)	AS CADASTRO 
		,
		(SELECT COUNT(*) FROM dbo.VW_CLIENTE)			AS CLIENTE 
		,(SELECT COUNT(*) FROM dbo.VW_FORNECEDOR)		AS FORNECEDOR
		,(SELECT COUNT(*) FROM dbo.VW_TRANSPORTADORA)	AS TRANSPORTADORA 
		,
		(SELECT COUNT(*) FROM dbo.VW_PRODUTO)	AS PRODUTO 
		,
		(SELECT COUNT(*) FROM dbo.VW_CLIENTE) +
		(SELECT COUNT(*) FROM dbo.VW_FORNECEDOR) +
		(SELECT COUNT(*) FROM dbo.VW_TRANSPORTADORA) +
		(SELECT COUNT(*) FROM dbo.VW_PRODUTO)	AS TOTAL
		,
		CAST((SELECT SUM(ESTOQUE_ATUAL) FROM dbo.VW_ESTOQUE) AS FLOAT)			AS ESTOQUE

	FROM sys.servers
END;
ROLLBACK TRANSACTION;
PRINT N'TESTESTESTESTSETSETSETSES TESTE';
GO
/*
REBOBINADO
*/