/* ETAPA 1: ALTERAR A/S PROCEDURE/S:
- SP_CHANGE_TABLET_EXECUTE
- SP_SET_CHANGE_TABLET
- SP_SET_CHANGE

VERIFICAR_SP_SET_CHANGES
*/
SET TERM ^ ;
ALTER PROCEDURE SP_SET_CHANGE (
    TABLE_NAME Varchar(30),
    PK_FIELD Varchar(40),
    PK_VALUE Varchar(40),
    TYPE_OPERATION Char(1) )
AS
     begin
     end^
SET TERM ; ^
COMMIT;

/* ETAPA 2: ALTERAR A PROCEDURE:
- SP_GET_GENERATOR

RETIRAR O ID DE BASE: ||''0X''
*/
ABRIR E EDITAR "SP_GET_GENERATOR"

/* ETAPA 3: DROPAR A/S TABLE/S:
- CHANGE_SATELITE
- CHANGE_CENTRAL
*/
DROP TABLE CHANGE_SATELITE;
COMMIT;

/* ETAPA 4: DROPAR O/S GENERATOR/S:
- GEN_CHANGE_TABLET
- GEN_CHANGE_SATELITE
- GEN_CHANGE_CENTRAL

DROPAR GENERATOR
*/
DROP GENERATOR GEN_CHANGE_SATELITE;
COMMIT;

/* ETAPA 5: EXECUTAR GENERATOR:
- SP_SET_ALL_GENERATOR
*/
EXECUTE PROCEDURE SP_SET_ALL_GENERATOR;
COMMIT;