::SETUP
::@ECHO OFF
CLS
@CHCP 1252>NUL
SETLOCAL ENABLEEXTENSIONS
SETLOCAL ENABLEDELAYEDEXPANSION
@SET PATH_DEV=Z:\DEV
@SET "_TAB=    "
@SET MSG_INPUT_PATH=PASTA DO PROJETO:
@SET MSG_INPUT_FILE=ARQUIVO #:
@SET MSG_ERRO_NOINPUT=ENTRADA NULA
@SET MSG_ERRO_NOPATH=CAMINHO NÃO ENCONTRADO
::MAIN
@SET /P "_PATH_INPUT=%MSG_INPUT_PATH% "||SET "_PATH_INPUT=NULO"
IF "!_PATH_INPUT!" NEQ "NULO" (
	@SET "PATH_PROJETO=!_PATH_INPUT!"
	IF EXIST "!PATH_PROJETO!" (
		@SET "COUNTER="
		FOR /F "TOKENS=*" %%C IN ('DIR /O:-D /T:C /B /A:-D "!PATH_PROJETO!"') DO (
			@SET /A "COUNTER+=1"
			::@ECHO %_TAB%!COUNTER!.%%C
		)
		@SET /P "_FILE_INPUT=%MSG_INPUT_FILE% "||SET "_FILE_INPUT=NULO"
		@SET "COUNTER="
		FOR /F "TOKENS=*" %%A IN ('DIR /O:-D /T:C /B /A:-D "!PATH_PROJETO!"') DO (
			@SET /A "COUNTER+=1"
			IF "!COUNTER!"=="!_FILE_INPUT!" (
				SET "_PATH_FILE=%%A"||SET "_PATH_FILE=NULO"
			)
		)
		IF "!_PATH_FILE!" NEQ "NULO" (
			@SET "PATH_WORKFILE=!PATH_PROJETO!\!_PATH_FILE!"
			IF EXIST "!PATH_WORKFILE!" (
				ECHO ARQUIVO DE TRABALHO: !PATH_WORKFILE!
			) ELSE ECHO %MSG_ERRO_NOPATH%
		) ELSE ECHO %MSG_ERRO_NOPATH%
	) ELSE ECHO %MSG_ERRO_NOPATH%
) ELSE ECHO %MSG_ERRO_NOINPUT%

GOTO:EXIT
::FUNCTIONS

::END
:EXIT
PAUSE>NUL
