SET SQL DIALECT 3;

--SET NAMES UTF8;
--SET NAMES UNICODE_FSS;
SET NAMES WIN1252;

CREATE DATABASE 'C:\TEMP\DADOS_NOVA.FDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET WIN1252;
