program FuturaEFDTests;
{

  Delphi DUnit Test Project
  -------------------------
  This project contains the DUnit test framework and the GUI/Console test runners.
  Add "CONSOLE_TESTRUNNER" to the conditional defines entry in the project options
  to use the console test runner.  Otherwise the GUI test runner will be used by
  default.

}

{$IFDEF CONSOLE_TESTRUNNER}
{$APPTYPE CONSOLE}
{$ENDIF}

uses
  uT_TipoComum,
  uT_DadosGerais,
  uT_Login,
  uT_BaseDadosPadrao,
  uT_SysCfgGlobals,
  uT_CobrancaBancariaUtils,
  TestuTCad_MetodoPermanenteSaldoICMS in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\TestuTCad_MetodoPermanenteSaldoICMS.pas',
  uTCad_MetodoPermanenteSaldoICMS in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\uTCad_MetodoPermanenteSaldoICMS.pas',
  TestuTCad_MetodoPermanenteSaldo in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\TestuTCad_MetodoPermanenteSaldo.pas',
  uTCad_MetodoPermanenteSaldo in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\uTCad_MetodoPermanenteSaldo.pas',
  TestuTCad_PlanoContaContabil in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\TestuTCad_PlanoContaContabil.pas',
  uTCad_PlanoContaContabil in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\uTCad_PlanoContaContabil.pas',
  TestuTCad_SpedApuracaoICMSDifal in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\TestuTCad_SpedApuracaoICMSDifal.pas',
  uTCad_SpedApuracaoICMSDifal in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\uTCad_SpedApuracaoICMSDifal.pas',
  TestuTCad_SpedRegistroC112 in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\TestuTCad_SpedRegistroC112.pas',
  uTCad_SpedRegistroC112 in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\uTCad_SpedRegistroC112.pas',
  TestuTCad_SpedApuracaoICMSAjuste in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\TestuTCad_SpedApuracaoICMSAjuste.pas',
  uTCad_SpedApuracaoICMSAjuste in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\uTCad_SpedApuracaoICMSAjuste.pas',
  TestuTCad_SpedApuracaoICMSST in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\TestuTCad_SpedApuracaoICMSST.pas',
  uTCad_SpedApuracaoICMSST in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\uTCad_SpedApuracaoICMSST.pas',
  TestuTCad_SpedApuracaoICMSItem in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\TestuTCad_SpedApuracaoICMSItem.pas',
  uTCad_SpedApuracaoICMSItem in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\uTCad_SpedApuracaoICMSItem.pas',
  TestuTCad_SpedApuracaoICMS in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\TestuTCad_SpedApuracaoICMS.pas',
  uTCad_SpedApuracaoICMS in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\uTCad_SpedApuracaoICMS.pas',
  TestuTCad_SpedApuracaoIPI in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\TestuTCad_SpedApuracaoIPI.pas',
  uTCad_SpedApuracaoIPI in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\uTCad_SpedApuracaoIPI.pas',
  TestuTCad_SpedReceitaBrutaMensal in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\TestuTCad_SpedReceitaBrutaMensal.pas',
  uTCad_SpedReceitaBrutaMensal in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\uTCad_SpedReceitaBrutaMensal.pas',
  TestuTCad_SpedOpGeradoraContribuicao in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\TestuTCad_SpedOpGeradoraContribuicao.pas',
  uTCad_SpedOpGeradoraContribuicao in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\uTCad_SpedOpGeradoraContribuicao.pas',
  TestuTCns_PlanoContaContabil in '..\..\..\..\RepTmp\Fiscal\Geral\Consulta\RNGenerico\TestuTCns_PlanoContaContabil.pas',
  uTCns_PlanoContaContabil in '..\..\..\..\RepTmp\Fiscal\Geral\Consulta\RNGenerico\uTCns_PlanoContaContabil.pas',
  TestuTCns_SpedApuracaoICMSDifal in '..\..\..\..\RepTmp\Fiscal\Geral\Consulta\RNGenerico\TestuTCns_SpedApuracaoICMSDifal.pas',
  uTCns_SpedApuracaoICMSDifal in '..\..\..\..\RepTmp\Fiscal\Geral\Consulta\RNGenerico\uTCns_SpedApuracaoICMSDifal.pas',
  TestuTCns_SpedRegistroC112 in '..\..\..\..\RepTmp\Fiscal\Geral\Consulta\RNGenerico\TestuTCns_SpedRegistroC112.pas',
  uTCns_SpedRegistroC112 in '..\..\..\..\RepTmp\Fiscal\Geral\Consulta\RNGenerico\uTCns_SpedRegistroC112.pas',
  TestuTCns_SpedApuracaoICMSST in '..\..\..\..\RepTmp\Fiscal\Geral\Consulta\RNGenerico\TestuTCns_SpedApuracaoICMSST.pas',
  uTCns_SpedApuracaoICMSST in '..\..\..\..\RepTmp\Fiscal\Geral\Consulta\RNGenerico\uTCns_SpedApuracaoICMSST.pas',
  TestuTCns_SpedApuracaoICMS in '..\..\..\..\RepTmp\Fiscal\Geral\Consulta\RNGenerico\TestuTCns_SpedApuracaoICMS.pas',
  uTCns_SpedApuracaoICMS in '..\..\..\..\RepTmp\Fiscal\Geral\Consulta\RNGenerico\uTCns_SpedApuracaoICMS.pas',
  TestuTCns_SpedApuracaoIPI in '..\..\..\..\RepTmp\Fiscal\Geral\Consulta\RNGenerico\TestuTCns_SpedApuracaoIPI.pas',
  uTCns_SpedApuracaoIPI in '..\..\..\..\RepTmp\Fiscal\Geral\Consulta\RNGenerico\uTCns_SpedApuracaoIPI.pas',
  TestuTCns_SpedReceitaBrutaMensal in '..\..\..\..\RepTmp\Fiscal\Geral\Consulta\RNGenerico\TestuTCns_SpedReceitaBrutaMensal.pas',
  uTCns_SpedReceitaBrutaMensal in '..\..\..\..\RepTmp\Fiscal\Geral\Consulta\RNGenerico\uTCns_SpedReceitaBrutaMensal.pas',
  TestuTCns_SpedOpGeradoraContribuicao in '..\..\..\..\RepTmp\Fiscal\Geral\Consulta\RNGenerico\TestuTCns_SpedOpGeradoraContribuicao.pas',

  ifMov_DevolucaoVendaPropria in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Movimento\InterfaceGenerico\ifMov_DevolucaoVendaPropria.pas' {fMov_DevolucaoVendaPropria},
  uTOtr_CopiaNotaFiscal in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Outro\RNGenerico\uTOtr_CopiaNotaFiscal.pas',
  uTMov_VendaPedido in '..\..\..\..\RepTmp\Venda\Pedido\Movimento\RNGenerico\uTMov_VendaPedido.pas',
  uTOtr_PedidoEstoqueTrava in '..\..\..\..\RepTmp\Venda\Geral\Outro\RnGenerico\uTOtr_PedidoEstoqueTrava.pas',
  uTMov_PedidoItem in '..\..\..\..\RepTmp\Geral\Pedido\Movimento\RNGenerico\uTMov_PedidoItem.pas',
  uTMov_CompraPedido in '..\..\..\..\RepTmp\Compra\Pedido\Movimento\RNGenerico\uTMov_CompraPedido.pas',
  uTMov_ValidaDesconto in '..\..\..\..\RepTmp\Venda\Pedido\Movimento\RNGenerico\uTMov_ValidaDesconto.pas',
  uTOtr_PedidoDesconto in '..\..\..\..\RepTmp\Venda\Geral\Outro\RnGenerico\uTOtr_PedidoDesconto.pas',
  uTOtr_TravaOrcamentoToVenda in '..\..\..\..\RepTmp\Venda\Geral\Outro\RnGenerico\uTOtr_TravaOrcamentoToVenda.pas',
  ifOtr_CadProdListaDesejoList in '..\..\..\..\RepTmp\Venda\Geral\Outro\RnGenerico\ifOtr_CadProdListaDesejoList.pas' {FOtr_cadProdListaDesejoList},
  uTOTr_CadastroProdutoListaDesejo in '..\..\..\..\RepTmp\Venda\Geral\Outro\RnGenerico\uTOTr_CadastroProdutoListaDesejo.pas',
  uTOtr_TravaVendaSemEstoque in '..\..\..\..\RepTmp\Venda\Geral\Outro\RnGenerico\uTOtr_TravaVendaSemEstoque.pas',
  ifOtr_CadastroProdutoListaDesejo in '..\..\..\..\RepTmp\Venda\Geral\Outro\RnGenerico\ifOtr_CadastroProdutoListaDesejo.pas' {fOtr_CadastroProdutoListaDesejo},
  uTCns_ProdutoSaldo in '..\..\..\..\RepTmp\Estoque\Produto\Consulta\RNGenerico\uTCns_ProdutoSaldo.pas',
  uTOtr_LimiteDeVenda in '..\..\..\..\RepTmp\Venda\Pedido\Outro\RnGenerico\uTOtr_LimiteDeVenda.pas',
  uTMov_VendaPedidoItem in '..\..\..\..\RepTmp\Venda\Pedido\Movimento\RNGenerico\uTMov_VendaPedidoItem.pas',
  uTOtr_FiscalTributoCalculo in '..\..\..\..\RepTmp\Fiscal\Geral\Outros\RnGenerico\uTOtr_FiscalTributoCalculo.pas',
  uTOtr_ProdutoDesconto in '..\..\..\..\RepTmp\Estoque\Produto\Outro\RNGenerico\uTOtr_ProdutoDesconto.pas',
  uTOtr_PedidoItemRepetido in '..\..\..\..\RepTmp\Geral\Pedido\Outro\RNGenerico\uTOtr_PedidoItemRepetido.pas',
  uTOtr_ProdutoSaldo in '..\..\..\..\RepTmp\Estoque\Produto\Outro\RNGenerico\uTOtr_ProdutoSaldo.pas',
  uTOtr_RecalculaST in '..\..\..\..\RepTmp\Venda\Pedido\Outro\RnGenerico\uTOtr_RecalculaST.pas',
  uTMov_Pedido in '..\..\..\..\RepTmp\Geral\Pedido\Movimento\RNGenerico\uTMov_Pedido.pas',
  uTOtr_RecalculoPedido in '..\..\..\..\RepTmp\Geral\Pedido\Outro\RNGenerico\uTOtr_RecalculoPedido.pas',
  ifOtr_PedidoItemLoteCompra in '..\..\..\..\RepTmp\Compra\Pedido\Movimento\InterfaceGenerico\ifOtr_PedidoItemLoteCompra.pas' {fOtr_PedidoItemLoteCompra},
  uTMov_PedidoItemLote in '..\..\..\..\RepTmp\Geral\Pedido\Movimento\RNGenerico\uTMov_PedidoItemLote.pas',
  ifOtr_NfeManifestacaoDestinatarioMaisInfo in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Outro\InterfaceGenerico\ifOtr_NfeManifestacaoDestinatarioMaisInfo.pas' {fOtr_NfeManifestacaoDestinatarioMaisInfo},
  uTCns_NotaFiscalNsu in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Consulta\RNGenerico\uTCns_NotaFiscalNsu.pas',
  uTCns_NotaFiscalNFEManDest in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Consulta\RNGenerico\uTCns_NotaFiscalNFEManDest.pas',
  uTOtr_NfeManifestacaoDestinatario in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Outro\RNGenerico\uTOtr_NfeManifestacaoDestinatario.pas',
  ifOtr_NfeManifestacaoDestinatarioMaisInfoEventos in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Outro\InterfaceGenerico\ifOtr_NfeManifestacaoDestinatarioMaisInfoEventos.pas' {fOtr_NfeManifestacaoDestinatarioMaisInfoEventos},
  uTOtr_SpedFiscalRessarcimento in '..\..\..\..\RepTmp\Fiscal\Geral\Outros\RnGenerico\uTOtr_SpedFiscalRessarcimento.pas',
  ifMov_NotaFiscalOutrasInformacoes in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Movimento\InterfaceGenerico\ifMov_NotaFiscalOutrasInformacoes.pas' {fMov_NotaFiscalOutrasInformacoes},
  ifExp_EFiscalWin in '..\..\..\..\RepTmp\Fiscal\Geral\Exportacao\InterfaceGenerico\ifExp_EFiscalWin.pas' {fExp_EFiscalWin},
  uTExp_EFiscalWinTipos in '..\..\..\..\RepTmp\Fiscal\Geral\Exportacao\RNGenerico\uTExp_EFiscalWinTipos.pas',
  ifOtr_InventarioSintetico in '..\..\..\..\Repositorio\Movimento\Fiscal\Sintegra\InterfaceGenerico\ifOtr_InventarioSintetico.pas' {fOtr_InventarioSintetico},
  uTOtr_InventarioSinteticoManual in '..\..\..\..\RepTmp\Fiscal\Inventario\Outros\RnGenerico\uTOtr_InventarioSinteticoManual.pas',
  ifOtr_InventarioSinteticoIndustria in '..\..\..\..\Repositorio\Movimento\Fiscal\Sintegra\InterfaceGenerico\ifOtr_InventarioSinteticoIndustria.pas' {fOtr_InventarioSinteticoIndustria},
  uTOtr_InventarioSinteticoIndustriaManual in '..\..\..\..\RepTmp\Fiscal\Inventario\Outros\RnGenerico\uTOtr_InventarioSinteticoIndustriaManual.pas',
  uTOtr_InventarioSinteticoIndustria in '..\..\..\..\Repositorio\Movimento\Fiscal\Sintegra\RnGenerico\uTOtr_InventarioSinteticoIndustria.pas',
  uTOtr_InventarioSinteticoIndustriaAnual in '..\..\..\..\Repositorio\Movimento\Fiscal\Sintegra\RnGenerico\uTOtr_InventarioSinteticoIndustriaAnual.pas',
  uTExp_EFiscalWin190 in '..\..\..\..\RepTmp\Fiscal\Geral\Exportacao\RNGenerico\uTExp_EFiscalWin190.pas',
  uTExp_Contimatic in '..\..\..\..\RepTmp\Fiscal\Geral\Exportacao\RNGenerico\uTExp_Contimatic.pas',
  ifExp_Contimatic in '..\..\..\..\RepTmp\Fiscal\Geral\Exportacao\InterfaceGenerico\ifExp_Contimatic.pas' {fExp_Contimatic},
  uTExp_EFiscalWin2006 in '..\..\..\..\RepTmp\Fiscal\Geral\Exportacao\RNGenerico\uTExp_EFiscalWin2006.pas',
  uTExp_EFiscalWin2005 in '..\..\..\..\RepTmp\Fiscal\Geral\Exportacao\RNGenerico\uTExp_EFiscalWin2005.pas',
  ifCad_NotaFiscalGNRE in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\InterfaceGenerico\ifCad_NotaFiscalGNRE.pas' {fCad_NotaFiscalGNRE},
  uTCad_NotaFiscalGNRE in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\uTCad_NotaFiscalGNRE.pas',
  uTCns_NotaFiscalGNRE in '..\..\..\..\RepTmp\Fiscal\Geral\Consulta\RNGenerico\uTCns_NotaFiscalGNRE.pas',
  uTOtr_LimpaInventario in '..\..\..\..\RepTmp\Fiscal\Inventario\Outros\RnGenerico\uTOtr_LimpaInventario.pas',
  ifOtr_LimpaInventario in '..\..\..\..\RepTmp\Fiscal\Inventario\Outros\InterfaceGenerico\ifOtr_LimpaInventario.pas' {fOtr_LimpaInventario},
  ifOtr_InventarioApuracaoST in '..\..\..\..\RepTmp\Fiscal\Inventario\Outros\InterfaceGenerico\ifOtr_InventarioApuracaoST.pas' {fOtr_InventarioApuracaoST},
  uTOtr_InventarioApuracaoSTToGARE in '..\..\..\..\RepTmp\Fiscal\Inventario\Outros\RnGenerico\uTOtr_InventarioApuracaoSTToGARE.pas',
  uTCns_InventarioApuracaoST in '..\..\..\..\RepTmp\Fiscal\Inventario\Consulta\RnGenerico\uTCns_InventarioApuracaoST.pas',
  uTExp_InventarioApuracaoST in '..\..\..\..\RepTmp\Fiscal\Inventario\Exportacao\RNGenerico\uTExp_InventarioApuracaoST.pas',
  ifCad_InventarioSaldoInicial in '..\..\..\..\RepTmp\Fiscal\Inventario\Cadastro\InterfaceGenerico\ifCad_InventarioSaldoInicial.pas' {fCad_NFInventarioSaldoInicial},
  uTExp_EFiscalWin200 in '..\..\..\..\RepTmp\Fiscal\Geral\Exportacao\RNGenerico\uTExp_EFiscalWin200.pas',
  uTOtr_RegerarCupom in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Outro\RNGenerico\uTOtr_RegerarCupom.pas',
  uTCns_InventarioSaldoInicial in '..\..\..\..\RepTmp\Fiscal\Inventario\Consulta\RnGenerico\uTCns_InventarioSaldoInicial.pas',
  uTCad_InventarioSaldoInicial in '..\..\..\..\RepTmp\Fiscal\Inventario\Cadastro\RNGenerico\uTCad_InventarioSaldoInicial.pas',
  ifOtr_RegerarCupomSelecionarProduto in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Outro\InterfaceGenerico\ifOtr_RegerarCupomSelecionarProduto.pas' {fOtr_RegerarCupomSelecionarProduto},
  ifOtr_RegerarArquivosSPED in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Outro\InterfaceGenerico\ifOtr_RegerarArquivosSPED.pas' {fOtr_RegerarArquivosSPED},
//  ifrm_BarraModular in '..\..\..\..\RepTmp\Diverso\Util\Outros\InterfaceGenerico\ifrm_BarraModular.pas' {frm_BarraModular: TFrame},
  uTOtr_ReplicacaoTipos in '..\..\..\..\RepTmp\Geral\Geral\Outro\RnGenerico\uTOtr_ReplicacaoTipos.pas',
  ifCfg_StatusReplicacao in '..\..\..\..\RepTmp\Geral\Geral\Configuracao\InterfaceGenerico\ifCfg_StatusReplicacao.pas' {fCfg_StatusReplicacao},
  uTCfg_StatusReplicacao in '..\..\..\..\RepTmp\Geral\Geral\Configuracao\RNGenerico\uTCfg_StatusReplicacao.pas',
//  ifCfg_CoresSistema in '..\..\..\..\RepTmp\Diverso\Util\Configuracao\InterfaceGenerico\ifCfg_CoresSistema.pas' {fCfg_CoresSistema},
  uTCad_Usuario in '..\..\..\..\RepTmp\Geral\Geral\Cadastro\RnGenerico\uTCad_Usuario.pas',
  uTCad_UsuarioModulo in '..\..\..\..\RepTmp\Geral\Geral\Cadastro\RnGenerico\uTCad_UsuarioModulo.pas',
  uTCad_CoresSistemaUsuario in '..\..\..\..\RepTmp\Diverso\Util\Cadastro\RnGenerico\uTCad_CoresSistemaUsuario.pas',
  uTCfg_Parametro in '..\..\..\..\RepTmp\Geral\Geral\Configuracao\RNGenerico\uTCfg_Parametro.pas',
  uTTipos in '..\..\Comum\uTTipos.pas',
  uTCad_CoresSistemaParametros in '..\..\..\..\RepTmp\Diverso\Util\Cadastro\RnGenerico\uTCad_CoresSistemaParametros.pas',
  uTOtr_AgendaControle in '..\..\..\..\RepTmp\Diverso\Util\Outros\RnGenerico\uTOtr_AgendaControle.pas',
  ifOtr_Agenda in '..\..\..\..\RepTmp\Diverso\Util\Outros\InterfaceGenerico\ifOtr_Agenda.pas' {fOtr_Agenda},
  uTSel_CtaParcelaReceberVencida in '..\..\..\..\RepTmp\Financeiro\ContaReceber\Selecao\RnGenerico\uTSel_CtaParcelaReceberVencida.pas',
  uTCns_CadastroAgendaContaParcela in '..\..\..\..\RepTmp\Geral\Cadastro\Consulta\RNGenerico\uTCns_CadastroAgendaContaParcela.pas',
  uTOtr_ContaBaixar in '..\..\..\..\RepTmp\Financeiro\Conta\Outros\RNGenerico\uTOtr_ContaBaixar.pas',
  uTSel_CtaReceberGerarBoleto in '..\..\..\..\RepTmp\Financeiro\ContaReceber\Selecao\RnGenerico\uTSel_CtaReceberGerarBoleto.pas',
  uTSel_CtaReceberBaixa in '..\..\..\..\RepTmp\Financeiro\ContaReceber\Selecao\RnGenerico\uTSel_CtaReceberBaixa.pas',
  uTSel_ContaParcelaBaixar in '..\..\..\..\RepTmp\Financeiro\Conta\Selecao\RnGenerico\uTSel_ContaParcelaBaixar.pas',
  iFOtr_ContaParcelaEnvioEmailBoleto in '..\..\..\..\RepTmp\Financeiro\ContaReceber\Outros\InterfaceGenerico\iFOtr_ContaParcelaEnvioEmailBoleto.pas' {FOtr_ContaParcelaEnvioEmailBoleto},
  uTOtr_PrintLayOutSangriaSuprimento in '..\..\..\..\RepTmp\Diverso\LayOut\Outros\RnGenerico\uTOtr_PrintLayOutSangriaSuprimento.pas',
  uTOtr_LayOutTipos in '..\..\..\..\RepTmp\Diverso\LayOut\Outros\RnGenerico\uTOtr_LayOutTipos.pas',
  uTOtr_PrintLayOut in '..\..\..\..\RepTmp\Diverso\LayOut\Outros\RnGenerico\uTOtr_PrintLayOut.pas',
  ifCad_ClienteEmChines in '..\..\..\..\RepTmp\Geral\Cadastro\Cadastro\InterfaceGenerico\ifCad_ClienteEmChines.pas' {fCad_ClienteEmChines},
  uTCad_Cliente in '..\..\..\..\RepTmp\Geral\Cadastro\Cadastro\RnGenerico\uTCad_Cliente.pas',
  uTCad_Cadastro in '..\..\..\..\RepTmp\Geral\Cadastro\Cadastro\RnGenerico\uTCad_Cadastro.pas',
  uTOtr_NotaFiscalEletronicaConsultaCadastro in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Outro\RNGenerico\uTOtr_NotaFiscalEletronicaConsultaCadastro.pas',
  uTOtr_NotaFiscalEletronicaSetCfgACBrNFe in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Outro\RNGenerico\uTOtr_NotaFiscalEletronicaSetCfgACBrNFe.pas',
  uTExp_NotaFiscalEletronicaPre in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Exportacao\RNGenerico\uTExp_NotaFiscalEletronicaPre.pas',
  uTExp_NotaFiscalEletronica in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Exportacao\RNGenerico\uTExp_NotaFiscalEletronica.pas',
  uTExp_NotaFiscalEletronicaTipos in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Exportacao\RNGenerico\uTExp_NotaFiscalEletronicaTipos.pas',
  uTOtr_NotaFiscalSetNumero in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Outro\RNGenerico\uTOtr_NotaFiscalSetNumero.pas',
  uTOtr_NotaFiscalNumero in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Outro\RNGenerico\uTOtr_NotaFiscalNumero.pas',
  uTOtr_NotaFiscalNFEXML in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Outro\RNGenerico\uTOtr_NotaFiscalNFEXML.pas',
  mDMRel_NotaFiscalEletronicaDanfeXML in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Relatorio\RNGenerico\mDMRel_NotaFiscalEletronicaDanfeXML.pas' {DMRel_NotaFiscalEletronicaDanfeXML: TDataModule},
  uTOtr_NfeConstantes in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Outro\RNGenerico\uTOtr_NfeConstantes.pas',
  uTOtr_NfeXMLCancelamento in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Outro\RNGenerico\uTOtr_NfeXMLCancelamento.pas',
  uTOtr_NotaFiscalCancelar in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Outro\RNGenerico\uTOtr_NotaFiscalCancelar.pas',
  uTOtr_NotaFiscalRedf in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Outro\RNGenerico\uTOtr_NotaFiscalRedf.pas',
  uTOtr_NotaFiscalEletronicaGeradorXML in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Outro\RNGenerico\uTOtr_NotaFiscalEletronicaGeradorXML.pas',
  mDMRel_NotaFiscalEletronicaConsumidorDanfe in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Relatorio\RNGenerico\mDMRel_NotaFiscalEletronicaConsumidorDanfe.pas' {DMRel_NotaFiscalEletronicaConsumidorDanfe: TDataModule},
  uTOtr_NFCeGeracaoEmTexto in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Outro\RNGenerico\uTOtr_NFCeGeracaoEmTexto.pas',
  ifCad_ProdutoValidacao in '..\..\..\..\RepTmp\Estoque\Produto\Cadastro\InterfaceGenerico\ifCad_ProdutoValidacao.pas' {fCad_ProdutoValidacao},
  uTCad_ProdutoValidacao in '..\..\..\..\RepTmp\Estoque\Produto\Cadastro\RNGenerico\uTCad_ProdutoValidacao.pas',
  uTCad_Produto in '..\..\..\..\RepTmp\Estoque\Produto\Cadastro\RNGenerico\uTCad_Produto.pas',
  uTCad_ProdutoGrade in '..\..\..\..\RepTmp\Estoque\Produto\Cadastro\RNGenerico\uTCad_ProdutoGrade.pas',
  bPF_Consulta in '..\..\Comum\bPF_Consulta.pas',
  bPF_ConsultaComum in '..\..\..\..\RepTmp\Diverso\Util\Consulta\RNGenerico\bPF_ConsultaComum.pas',
  uTCad_ProdutoPreco in '..\..\..\..\RepTmp\Estoque\Produto\Cadastro\RNGenerico\uTCad_ProdutoPreco.pas',
  uTOtr_ProdutoPrecoAtualiza in '..\..\..\..\RepTmp\Estoque\Produto\Outro\RNGenerico\uTOtr_ProdutoPrecoAtualiza.pas',
  uTCad_ProdutoGradeValor in '..\..\..\..\RepTmp\Estoque\Produto\Cadastro\RNGenerico\uTCad_ProdutoGradeValor.pas',
  uTCad_ProdutoGradeFiscal in '..\..\..\..\RepTmp\Estoque\Produto\Cadastro\RNGenerico\uTCad_ProdutoGradeFiscal.pas',
  uTCad_ProdutoFiscal in '..\..\..\..\RepTmp\Estoque\Produto\Cadastro\RNGenerico\uTCad_ProdutoFiscal.pas',
  uTCns_BaseLegalAliquotas in '..\..\..\..\RepTmp\Fiscal\Geral\Consulta\RNGenerico\uTCns_BaseLegalAliquotas.pas',
  uTCad_ProdutoCodigoBarra in '..\..\..\..\RepTmp\Estoque\Produto\Cadastro\RNGenerico\uTCad_ProdutoCodigoBarra.pas',
  uTCad_ProdutoSituacaoTributaria in '..\..\..\..\RepTmp\Estoque\Produto\Cadastro\RNGenerico\uTCad_ProdutoSituacaoTributaria.pas',
  uTOtr_ContaDocumentoUpdate in '..\..\..\..\RepTmp\Financeiro\Geral\Outros\RnGenerico\uTOtr_ContaDocumentoUpdate.pas',
  mDMRel_NotaFiscalEletronicaDanfe in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Relatorio\RNGenerico\mDMRel_NotaFiscalEletronicaDanfe.pas' {DMRel_NotaFiscalEletronicaDanfe: TDataModule},
  uTOtr_NotaFiscalObservacaoSet in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Outro\RNGenerico\uTOtr_NotaFiscalObservacaoSet.pas',
  uTOtr_NotaFiscalNFESendEmail in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Outro\RNGenerico\uTOtr_NotaFiscalNFESendEmail.pas',
  ifCad_CadastroAlterar in '..\..\..\..\RepTmp\Geral\Cadastro\Cadastro\InterfaceGenerico\ifCad_CadastroAlterar.pas' {fCad_CadastroAlterar},
  uTCad_CadastroEnderecoFaturamento in '..\..\..\..\RepTmp\Geral\Cadastro\Cadastro\RnGenerico\uTCad_CadastroEnderecoFaturamento.pas',
  uTCad_CadastroEndereco in '..\..\..\..\RepTmp\Geral\Cadastro\Cadastro\RnGenerico\uTCad_CadastroEndereco.pas',
  uTOtr_CadastroValidar in '..\..\..\..\RepTmp\Geral\Cadastro\Cadastro\RnGenerico\uTOtr_CadastroValidar.pas',
  ifCns_CEPTouch in '..\..\..\..\RepTmp\Diverso\ConsultaCEP\Outros\InterfaceGenerico\ifCns_CEPTouch.pas' {fCns_CEPTouch},
  ifCns_CEP in '..\..\..\..\RepTmp\Diverso\ConsultaCEP\Outros\InterfaceGenerico\ifCns_CEP.pas' {fCns_CEP},
  uTCns_CEP in '..\..\..\..\RepTmp\Geral\Geral\Consulta\RnGenerico\uTCns_CEP.pas',
  ifOtr_NotaFiscalNFEContigencia in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Outro\InterfaceGenerico\ifOtr_NotaFiscalNFEContigencia.pas' {fOtr_NotaFiscalNFEContigencia},
  uTMov_NotaFiscal in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Movimento\RnGenerico\uTMov_NotaFiscal.pas',
  uTOtr_NotaFiscalRecalculo in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Outro\RNGenerico\uTOtr_NotaFiscalRecalculo.pas',
  uTCad_CadastroSimplesNacionalICMS in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\uTCad_CadastroSimplesNacionalICMS.pas',
  ifCad_CadastroSimplesNacionalICMSSimples in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\InterfaceGenerico\ifCad_CadastroSimplesNacionalICMSSimples.pas' {fCad_CadastroSimplesNacionalICMSSimples},
  uTMov_NotaFiscalItem in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Movimento\RnGenerico\uTMov_NotaFiscalItem.pas',
  uTOtr_UpdateProdutoFornecedorCusto in '..\..\..\..\RepTmp\Estoque\Produto\Outro\RNGenerico\uTOtr_UpdateProdutoFornecedorCusto.pas',
  uTOtr_UpdateProdutoSubsTrib in '..\..\..\..\RepTmp\Geral\Geral\Outro\RnGenerico\uTOtr_UpdateProdutoSubsTrib.pas',
  uTOtr_UpdateProdutoOrigem in '..\..\..\..\RepTmp\Estoque\Produto\Outro\RNGenerico\uTOtr_UpdateProdutoOrigem.pas',
  uTOtr_AdicionaProdFornecedor in '..\..\..\..\RepTmp\Compra\Pedido\Outro\RNGenerico\uTOtr_AdicionaProdFornecedor.pas',
  uTCad_CadastroFiscal in '..\..\..\..\RepTmp\Geral\Cadastro\Cadastro\RnGenerico\uTCad_CadastroFiscal.pas',
  iFOtr_ConsultaCNPJReceitaCaptcha in '..\..\..\..\RepTmp\Geral\Cadastro\Outro\InterfaceGenerico\iFOtr_ConsultaCNPJReceitaCaptcha.pas' {FOtr_ConsultaCNPJReceitaCaptcha},
  uTOtr_ConsultaCNPJReceita in '..\..\..\..\RepTmp\Geral\Cadastro\Outro\RnGenerico\uTOtr_ConsultaCNPJReceita.pas',
  uTSel_NotaFiscalLote in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Selecao\RnGenerico\uTSel_NotaFiscalLote.pas',
  uTSel_NotaFiscal in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Selecao\RnGenerico\uTSel_NotaFiscal.pas',
  ifCad_CadastroSimples in '..\..\..\..\RepTmp\Geral\Cadastro\Cadastro\InterfaceGenerico\ifCad_CadastroSimples.pas' {fCad_CadastroSimples},
  uTOtr_NotaFiscalEletronicaConsultaServico in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Outro\RNGenerico\uTOtr_NotaFiscalEletronicaConsultaServico.pas',
  uTCns_Cliente in '..\..\..\..\RepTmp\Geral\Cadastro\Consulta\RNGenerico\uTCns_Cliente.pas',
  uTCns_Cadastro in '..\..\..\..\RepTmp\Geral\Cadastro\Consulta\RNGenerico\uTCns_Cadastro.pas',
  ifCad_ProdutoEmChines in '..\..\..\..\RepTmp\Estoque\Produto\Cadastro\InterfaceGenerico\ifCad_ProdutoEmChines.pas' {fCad_ProdutoEmChines},
  uTCns_Produto in '..\..\..\..\RepTmp\Estoque\Produto\Consulta\RNGenerico\uTCns_Produto.pas',
  uTCns_TabelaPreco in '..\..\..\..\RepTmp\Geral\Geral\Consulta\RnGenerico\uTCns_TabelaPreco.pas',
  uTOtr_ConsultaProdutoEstoque in '..\..\..\..\RepTmp\Estoque\Produto\Outro\RNGenerico\uTOtr_ConsultaProdutoEstoque.pas',
  ifMov_NotaFiscalSimplificada in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Movimento\InterfaceGenerico\ifMov_NotaFiscalSimplificada.pas' {fMov_NotaFiscalSimplificada},
  uTMov_NotaFiscalVendaSimplificado in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Movimento\RnGenerico\uTMov_NotaFiscalVendaSimplificado.pas',
  uTMov_NotaFiscalItemSimplificado in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Movimento\RnGenerico\uTMov_NotaFiscalItemSimplificado.pas',
  uTSel_NotaFiscalImprimir in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Selecao\RnGenerico\uTSel_NotaFiscalImprimir.pas',
  uTOtr_PrintLayOutNotaFiscal in '..\..\..\..\RepTmp\Diverso\LayOut\Outros\RnGenerico\uTOtr_PrintLayOutNotaFiscal.pas',
  uTOtr_GNREExportar in '..\..\..\..\RepTmp\Fiscal\Geral\Outros\RnGenerico\uTOtr_GNREExportar.pas',
  uTExp_GNRE in '..\..\..\..\RepTmp\Fiscal\Geral\Exportacao\RNGenerico\uTExp_GNRE.pas',
  uTExp_GNREOnline in '..\..\..\..\RepTmp\Fiscal\Geral\Exportacao\RNGenerico\uTExp_GNREOnline.pas',
  ifOtr_ConsultaTipo in '..\..\..\..\RepTmp\Geral\Geral\Outro\InterfaceGenerico\ifOtr_ConsultaTipo.pas' {fOtr_ConsultaTipo},
  uTExp_GNREOnlineWebService in '..\..\..\..\RepTmp\Fiscal\Geral\Exportacao\RNGenerico\uTExp_GNREOnlineWebService.pas',
  ifCns_BaseLegalDescricao in '..\..\..\..\RepTmp\Fiscal\Geral\Consulta\InterfaceGenerico\ifCns_BaseLegalDescricao.pas' {fCns_BaseLegalDescricao},
  uTCns_BaseLegalDescricao in '..\..\..\..\RepTmp\Fiscal\Geral\Consulta\RNGenerico\uTCns_BaseLegalDescricao.pas',
  ifCns_ICMS in '..\..\..\..\RepTmp\Fiscal\Geral\Consulta\InterfaceGenerico\ifCns_ICMS.pas' {fCns_ICMS},
  uTCns_ICMS_UF in '..\..\..\..\RepTmp\Fiscal\Geral\Consulta\RNGenerico\uTCns_ICMS_UF.pas',
  uTCns_ProdutoFiscalGrupo in '..\..\..\..\RepTmp\Estoque\Produto\Consulta\RNGenerico\uTCns_ProdutoFiscalGrupo.pas',
  uTOtr_ProdutoICMSCSTPadrao in '..\..\..\..\RepTmp\Estoque\Produto\Outro\RNGenerico\uTOtr_ProdutoICMSCSTPadrao.pas',
  iFrm_CadastroFiscalChines in '..\..\..\..\RepTmp\Estoque\Produto\Cadastro\InterfaceGenerico\iFrm_CadastroFiscalChines.pas' {Frm_CadastroFiscalChines: TFrame},
  ifCad_Empresa in '..\..\..\..\RepTmp\Geral\Cadastro\Cadastro\InterfaceGenerico\ifCad_Empresa.pas' {fCad_Empresa},
  ifRel_ProdutoNroLote in '..\..\..\..\RepTmp\Venda\Geral\Relatorio\InterfaceGenerico\ifRel_ProdutoNroLote.pas' {fRel_ProdutoNroLote},
  mDMRel_ProdutoNroLote in '..\..\..\..\RepTmp\Venda\Geral\Relatorio\RnGenerico\mDMRel_ProdutoNroLote.pas' {DMRel_ProdutoNroLote: TDataModule},
  uTCad_Empresa in '..\..\..\..\RepTmp\Geral\Cadastro\Cadastro\RnGenerico\uTCad_Empresa.pas',
  uTCns_Empresa in '..\..\..\..\RepTmp\Geral\Cadastro\Consulta\RNGenerico\uTCns_Empresa.pas',
  uTCad_CadastroEnderecoCobranca in '..\..\..\..\RepTmp\Geral\Cadastro\Cadastro\RnGenerico\uTCad_CadastroEnderecoCobranca.pas',
  uTCad_CadastroContribuinteSubstituto in '..\..\..\..\RepTmp\Geral\Cadastro\Cadastro\RnGenerico\uTCad_CadastroContribuinteSubstituto.pas',
  uTOtr_CopiaEndereco in '..\..\..\..\RepTmp\Geral\Cadastro\Outro\RnGenerico\uTOtr_CopiaEndereco.pas',
  ifMov_NotaFiscal in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Movimento\InterfaceGenerico\ifMov_NotaFiscal.pas' {fMov_NotaFiscal},
  ifMov_NotaFiscalItemMedicamento in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Movimento\InterfaceGenerico\ifMov_NotaFiscalItemMedicamento.pas' {fMov_NotaFiscalItemMedicamento},
  uTMov_NotaFiscalItemMedicamento in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Movimento\RnGenerico\uTMov_NotaFiscalItemMedicamento.pas',
  ifMov_NotaFiscalItemPapelImune in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Movimento\InterfaceGenerico\ifMov_NotaFiscalItemPapelImune.pas' {fMov_NotaFiscalItemPapelImune},
  uTMov_NotaFiscalItemPapelImune in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Movimento\RnGenerico\uTMov_NotaFiscalItemPapelImune.pas',
  uTCns_NotaFiscal in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Consulta\RNGenerico\uTCns_NotaFiscal.pas',
  ifMov_NotaFiscalItemCombustiveis in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Movimento\InterfaceGenerico\ifMov_NotaFiscalItemCombustiveis.pas' {fMov_NotaFiscalItemCombustiveis},
  uTMov_NotaFiscalItemCombustiveis in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Movimento\RnGenerico\uTMov_NotaFiscalItemCombustiveis.pas',
  uTMov_NotaFiscalItemServico in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Movimento\RnGenerico\uTMov_NotaFiscalItemServico.pas',
  uTMov_NotaFiscalOutroImposto in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Movimento\RnGenerico\uTMov_NotaFiscalOutroImposto.pas',
  uTMov_NotaFiscalOutrasInfo in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Movimento\RnGenerico\uTMov_NotaFiscalOutrasInfo.pas',
  ifMov_NotaFiscalItemArmamentos in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Movimento\InterfaceGenerico\ifMov_NotaFiscalItemArmamentos.pas' {fMov_NotaFiscalItemArmamentos},
  uTMov_NotaFiscalItemArmamentos in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Movimento\RnGenerico\uTMov_NotaFiscalItemArmamentos.pas',
  ifMov_NotaFiscalItemExportacao in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Movimento\InterfaceGenerico\ifMov_NotaFiscalItemExportacao.pas' {fMov_NotaFiscalItemExportacao},
  uTMov_NotaFiscalItemExportacao in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Movimento\RnGenerico\uTMov_NotaFiscalItemExportacao.pas',
  ifCns_ProdutoNroSeries in '..\..\..\..\RepTmp\Geral\Cadastro\Consulta\InterfaceGenerico\ifCns_ProdutoNroSeries.pas' {fCns_ProdutoNroSeries},
  uTCns_ProdutoNroSeries in '..\..\..\..\RepTmp\Geral\Cadastro\Consulta\RNGenerico\uTCns_ProdutoNroSeries.pas',
  uTCns_NotaFiscalLote in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Consulta\RNGenerico\uTCns_NotaFiscalLote.pas',
  uTMov_NotaFiscalAntecipacaoSTEntrada in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Movimento\RnGenerico\uTMov_NotaFiscalAntecipacaoSTEntrada.pas',
  uTMov_NotaFiscalAntecipacaoST in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Movimento\RnGenerico\uTMov_NotaFiscalAntecipacaoST.pas',
  uTCns_NotaFiscalNFE in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Consulta\RNGenerico\uTCns_NotaFiscalNFE.pas',
  uTOtr_NotaFiscalAntecipacaoSTCalculo in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Outro\RNGenerico\uTOtr_NotaFiscalAntecipacaoSTCalculo.pas',
  uTOtr_ProdutoSubstituicaoTributariaSet in '..\..\..\..\RepTmp\Estoque\Produto\Outro\RNGenerico\uTOtr_ProdutoSubstituicaoTributariaSet.pas',
  uTMov_NotaFiscalItemRetAnt in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Movimento\RnGenerico\uTMov_NotaFiscalItemRetAnt.pas',
  uTOtr_NfeXmlToNotaFiscal in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Outro\RNGenerico\uTOtr_NfeXmlToNotaFiscal.pas',
  uTMov_NotaFiscalItemVeiculosNovos in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Movimento\RnGenerico\uTMov_NotaFiscalItemVeiculosNovos.pas',
  uTMov_LotePedidoItem in '..\..\..\..\RepTmp\Estoque\Pedido\Movimento\RnGenerico\uTMov_LotePedidoItem.pas',
  uTMov_PedidoItemGarantia in '..\..\..\..\RepTmp\Geral\Pedido\Movimento\RNGenerico\uTMov_PedidoItemGarantia.pas',
  uTOtr_PedidoToContaPagar in '..\..\..\..\RepTmp\Financeiro\ContaPagar\Outros\RnGenerico\uTOtr_PedidoToContaPagar.pas',
  uTMov_ContaPagar in '..\..\..\..\RepTmp\Financeiro\ContaPagar\Movimento\RnGenerico\uTMov_ContaPagar.pas',
  uTMov_Conta in '..\..\..\..\RepTmp\Financeiro\Conta\Movimento\RNGenerico\uTMov_Conta.pas',
  uTMov_ContaParcela_Renegociacao in '..\..\..\..\RepTmp\Financeiro\Conta\Movimento\RNGenerico\uTMov_ContaParcela_Renegociacao.pas',
  uTMov_ContaParcela in '..\..\..\..\RepTmp\Financeiro\Conta\Movimento\RNGenerico\uTMov_ContaParcela.pas',
  uTOtr_ContaParcelaGerar in '..\..\..\..\RepTmp\Financeiro\Conta\Outros\RNGenerico\uTOtr_ContaParcelaGerar.pas',
  uTMov_ContaParcela_Cancelada in '..\..\..\..\RepTmp\Financeiro\Conta\Movimento\RNGenerico\uTMov_ContaParcela_Cancelada.pas',
  uTCns_FaturaPrazoDia in '..\..\..\..\RepTmp\Financeiro\Geral\Consulta\RnGenerico\uTCns_FaturaPrazoDia.pas',
  ifOtr_MovimentoFatura in '..\..\..\..\RepTmp\Financeiro\ContaReceber\Outros\InterfaceGenerico\ifOtr_MovimentoFatura.pas' {fOtr_MovimentoFatura},
  uTMov_ContaReceber in '..\..\..\..\RepTmp\Financeiro\ContaReceber\Movimento\RnGenerico\uTMov_ContaReceber.pas',
  ifMov_NotaFiscalItemOutrasInfo in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Movimento\InterfaceGenerico\ifMov_NotaFiscalItemOutrasInfo.pas' {fMov_NotaFiscalItemOutrasInfo},
  ifMov_NFTranspOutrasInfo in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Movimento\InterfaceGenerico\ifMov_NFTranspOutrasInfo.pas' {fMov_NFTranspOutrasInfo},
  uTOtr_PreNfeXmlToNotaFiscal in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Outro\RNGenerico\uTOtr_PreNfeXmlToNotaFiscal.pas',
  ifOtr_NfeXMLToNotaFiscalProdutoNew in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Outro\InterfaceGenerico\ifOtr_NfeXMLToNotaFiscalProdutoNew.pas' {fOtr_NfeXMLToNotaFiscalProdutoNew},
  uTOtr_NfeXMLToNotaFiscalProduto in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Outro\RNGenerico\uTOtr_NfeXMLToNotaFiscalProduto.pas',
  uTOtr_PreNfeXmlProdutoToProduto in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Outro\RNGenerico\uTOtr_PreNfeXmlProdutoToProduto.pas',
  uTCad_ProdutoFornecedor in '..\..\..\..\RepTmp\Estoque\Produto\Cadastro\RNGenerico\uTCad_ProdutoFornecedor.pas',
  uTOtr_PreNfeXmlDestinatarioToCadastro in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Outro\RNGenerico\uTOtr_PreNfeXmlDestinatarioToCadastro.pas',
  uTOtr_CadObservacao in '..\..\..\..\RepTmp\Geral\Cadastro\Outro\RnGenerico\uTOtr_CadObservacao.pas',
  uTCad_FiscalEnderecoRetirada in '..\..\..\..\RepTmp\Geral\Cadastro\Cadastro\RnGenerico\uTCad_FiscalEnderecoRetirada.pas',
  uTCad_CadastroEnderecoFiscal in '..\..\..\..\RepTmp\Geral\Cadastro\Cadastro\RnGenerico\uTCad_CadastroEnderecoFiscal.pas',
  uTCad_FiscalEnderecoLocalEntrega in '..\..\..\..\RepTmp\Geral\Cadastro\Cadastro\RnGenerico\uTCad_FiscalEnderecoLocalEntrega.pas',
  uTCns_NotaFiscalCartaCorrecao in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Consulta\RNGenerico\uTCns_NotaFiscalCartaCorrecao.pas',
  ifMov_NotaFiscalItemVeiculosNovos in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Movimento\InterfaceGenerico\ifMov_NotaFiscalItemVeiculosNovos.pas' {fMov_NotaFiscalItemVeiculosNovos},
  ifImp_NotaFiscalCompraDevolucao in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Importacao\InterfaceGenerico\ifImp_NotaFiscalCompraDevolucao.pas' {fImp_NotaFiscalCompraDevolucao},
  uTOtr_CompraDevolucaoItens in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Outro\RNGenerico\uTOtr_CompraDevolucaoItens.pas',
  uTOtr_GerarNotaFiscal in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Outro\RNGenerico\uTOtr_GerarNotaFiscal.pas',
  ifMov_NotaFiscalDigitacaoXML in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Movimento\InterfaceGenerico\ifMov_NotaFiscalDigitacaoXML.pas' {fMov_NotaFiscalDigitacaoXML},
  uTOtr_NotaFiscalDigitacaoXML in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Outro\RNGenerico\uTOtr_NotaFiscalDigitacaoXML.pas',
  uTMov_NotaFiscalAntiDumping in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Movimento\RnGenerico\uTMov_NotaFiscalAntiDumping.pas',
  uTMov_NotaFiscalCamposLivres in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Movimento\RnGenerico\uTMov_NotaFiscalCamposLivres.pas',
  uTMov_NotaFiscalDocReferenciado in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Movimento\RnGenerico\uTMov_NotaFiscalDocReferenciado.pas',
  uTOtr_NotaFiscalImportaPedido in '..\..\..\..\RepTmp\Geral\Geral\Outro\RnGenerico\uTOtr_NotaFiscalImportaPedido.pas',
  ifSel_NotaFiscalLote in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Selecao\InterfaceGenerico\ifSel_NotaFiscalLote.pas' {fSel_NotaFiscalLote},
  ifOtr_InventarioOnline in '..\..\..\..\RepTmp\Fiscal\Geral\Outros\InterfaceGenerico\ifOtr_InventarioOnline.pas' {fOtr_InventarioOnline},
  uTOtr_ItemDescricaoEspecifica in '..\..\..\..\RepTmp\Geral\Geral\Outro\RnGenerico\uTOtr_ItemDescricaoEspecifica.pas',
  uTOtr_NotaFiscalAntecipacaoSTToGare in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Outro\RNGenerico\uTOtr_NotaFiscalAntecipacaoSTToGare.pas',
  uTExp_GARE in '..\..\..\..\RepTmp\Fiscal\Geral\Exportacao\RNGenerico\uTExp_GARE.pas',
  ifOtr_NfeXMLToNotaFiscalImportacao in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Outro\InterfaceGenerico\ifOtr_NfeXMLToNotaFiscalImportacao.pas' {fOtr_NfeXMLToNotaFiscalImportacao},
  uTOtr_NfeXmlToNotaFiscalFactory in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Outro\RNGenerico\uTOtr_NfeXmlToNotaFiscalFactory.pas',
  uTOtr_NfeXmlToNotaFiscalEmissaoPropria in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Outro\RNGenerico\uTOtr_NfeXmlToNotaFiscalEmissaoPropria.pas',
  uTCad_Transportadora in '..\..\..\..\RepTmp\Geral\Cadastro\Cadastro\RnGenerico\uTCad_Transportadora.pas',
  ifCad_Cadastro in '..\..\..\..\RepTmp\Geral\Cadastro\Cadastro\InterfaceGenerico\ifCad_Cadastro.pas' {fCad_Cadastro},
  uTCad_Fornecedor in '..\..\..\..\RepTmp\Geral\Cadastro\Cadastro\RnGenerico\uTCad_Fornecedor.pas',
  ifCad_ProdutoFiscalSimples in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\InterfaceGenerico\ifCad_ProdutoFiscalSimples.pas' {fCad_ProdutoFiscalSimples},
  iFrm_CadastroFiscal in '..\..\..\..\RepTmp\Estoque\Produto\Cadastro\InterfaceGenerico\iFrm_CadastroFiscal.pas' {Frm_CadastroFiscal: TFrame},
  uTOtr_NfeXmlToNotaFiscalEmissaoTerceiros in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Outro\RNGenerico\uTOtr_NfeXmlToNotaFiscalEmissaoTerceiros.pas',
  uTOtr_NotaFiscalVerificaListaProdutos in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Outro\RNGenerico\uTOtr_NotaFiscalVerificaListaProdutos.pas',
  ifOtr_NfeXmlToNotaFiscalMultiplosProdutos in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Outro\InterfaceGenerico\ifOtr_NfeXmlToNotaFiscalMultiplosProdutos.pas' {fOtr_NfeXmlToNotaFiscalMultiplosProdutos},
  ifOtr_NfeXMLToNotaFiscalProduto in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Outro\InterfaceGenerico\ifOtr_NfeXMLToNotaFiscalProduto.pas' {fOtr_NfeXMLToNotaFiscalProduto},
  ifOtr_NotaFiscalPathEmail in '..\..\..\..\RepTmp\Fiscal\Geral\Outros\InterfaceGenerico\ifOtr_NotaFiscalPathEmail.pas' {fOtr_NotaFiscalPathEmail},
  uTOtr_ImportarEndereco in '..\..\..\..\RepTmp\Geral\Cadastro\Outro\RnGenerico\uTOtr_ImportarEndereco.pas',
  uTOtr_PedidoToNotaFiscal in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Outro\RNGenerico\uTOtr_PedidoToNotaFiscal.pas',
  uTOtr_PedidoToNotaFiscalDevolucaoDescontar in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Outro\RNGenerico\uTOtr_PedidoToNotaFiscalDevolucaoDescontar.pas',
  ifMov_CtaReceberBaixaSimples in '..\..\..\..\RepTmp\Financeiro\ContaReceber\Movimento\InterfaceGenerico\ifMov_CtaReceberBaixaSimples.pas' {fMov_CtaReceberBaixaSimples},
  uTSel_CtaReceberBaixaSimples in '..\..\..\..\RepTmp\Financeiro\ContaReceber\Selecao\RnGenerico\uTSel_CtaReceberBaixaSimples.pas',
  uTMov_FinanceiroCtaReceberBaixa in '..\..\..\..\RepTmp\Financeiro\Geral\Movimento\RnGenerico\uTMov_FinanceiroCtaReceberBaixa.pas',
  uTOtr_MovimentoCartao in '..\..\..\..\RepTmp\Financeiro\Geral\Outros\RnGenerico\uTOtr_MovimentoCartao.pas',
  uTMov_ContaParcela_Financeiro in '..\..\..\..\RepTmp\Financeiro\Conta\Movimento\RNGenerico\uTMov_ContaParcela_Financeiro.pas',
  uTCad_CadastroEnderecoEntrega in '..\..\..\..\RepTmp\Geral\Cadastro\Cadastro\RnGenerico\uTCad_CadastroEnderecoEntrega.pas',
  ifMov_NotaFiscalCorrecao in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Movimento\InterfaceGenerico\ifMov_NotaFiscalCorrecao.pas' {fMov_NotaFiscalCorrecao},
  uTOtr_NotaFiscalEletronicaCartaCorrecao in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Outro\RNGenerico\uTOtr_NotaFiscalEletronicaCartaCorrecao.pas',
  uTOtr_NotaFiscalCorrecaoCCeSendEmail in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Outro\RNGenerico\uTOtr_NotaFiscalCorrecaoCCeSendEmail.pas',
  mDMRel_NotaFiscalCorrecao in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Relatorio\RnGenerico\mDMRel_NotaFiscalCorrecao.pas' {DMRel_NotaFiscalCorrecao: TDataModule},
  uTMov_NotaFiscalCorrecao in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Movimento\RnGenerico\uTMov_NotaFiscalCorrecao.pas',
  uTCns_NotaFiscalCorrecao in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Consulta\RNGenerico\uTCns_NotaFiscalCorrecao.pas',
  uTOtr_NotaFiscalToContaReceber in '..\..\..\..\RepTmp\Financeiro\ContaReceber\Outros\RnGenerico\uTOtr_NotaFiscalToContaReceber.pas',
  ifMov_NotaFiscalOutrasInfo in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Movimento\InterfaceGenerico\ifMov_NotaFiscalOutrasInfo.pas' {fMov_NotaFiscalOutrasInfo},
  uTCns_NotaFiscalOutrasInfo in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Consulta\RNGenerico\uTCns_NotaFiscalOutrasInfo.pas',
  ifCad_SpedOpGeradoraContribuicao in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\InterfaceGenerico\ifCad_SpedOpGeradoraContribuicao.pas' {fCad_SpedOpGeradoraContribuicao},
  uTCns_SpedOpGeradoraContribuicao in '..\..\..\..\RepTmp\Fiscal\Geral\Consulta\RNGenerico\uTCns_SpedOpGeradoraContribuicao.pas',
//  uTCad_SpedOpGeradoraContribuicao in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\uTCad_SpedOpGeradoraContribuicao.pas',
  uTCns_Conta in '..\..\..\..\RepTmp\Financeiro\Conta\Consulta\RNGenerico\uTCns_Conta.pas',
  uTCns_ContaParcela in '..\..\..\..\RepTmp\Financeiro\Conta\Consulta\RNGenerico\uTCns_ContaParcela.pas',
  uTOtr_GeraDuplicataSpedF100 in '..\..\..\..\RepTmp\Financeiro\Conta\Outros\RNGenerico\uTOtr_GeraDuplicataSpedF100.pas',
  ifOtr_GeraDuplicata in '..\..\..\..\RepTmp\Financeiro\ContaPagar\Outros\InterfaceGenerico\ifOtr_GeraDuplicata.pas' {fOtr_GeraDuplicata},
  uTOtr_GeraDuplicata in '..\..\..\..\RepTmp\Financeiro\ContaPagar\Outros\RnGenerico\uTOtr_GeraDuplicata.pas',
  uTMov_ContaCentroCusto in '..\..\..\..\RepTmp\Financeiro\Conta\Movimento\RNGenerico\uTMov_ContaCentroCusto.pas',
  ifCns_ChequeEmitidoFinanceiro in '..\..\..\..\RepTmp\Financeiro\ContaPagar\Consulta\InterfaceGenerico\ifCns_ChequeEmitidoFinanceiro.pas' {fCns_ChequeEmitidoFinanceiro},
  uTCns_ConsultaCheque in '..\..\..\..\RepTmp\Venda\Geral\Consulta\RnGenerico\uTCns_ConsultaCheque.pas',
  uTCad_TalaoChequeItem in '..\..\..\..\RepTmp\Financeiro\Geral\Cadastro\RnGenerico\uTCad_TalaoChequeItem.pas',
  ifCns_ContaPagarParcelaFinanceiro in '..\..\..\..\RepTmp\Financeiro\ContaPagar\Consulta\InterfaceGenerico\ifCns_ContaPagarParcelaFinanceiro.pas' {fCns_ContaPagarParcelaFinanceiro},
  uTCns_FinanceiroContaPagarDetalhe in '..\..\..\..\RepTmp\Financeiro\ContaPagar\Consulta\RnGenerico\uTCns_FinanceiroContaPagarDetalhe.pas',
  uTMov_Financeiro in '..\..\..\..\RepTmp\Financeiro\Geral\Movimento\RnGenerico\uTMov_Financeiro.pas',
  uTCns_Financeiro in '..\..\..\..\RepTmp\Financeiro\Geral\Consulta\RnGenerico\uTCns_Financeiro.pas',
  uTMov_FinanceiroMovBancario in '..\..\..\..\RepTmp\Financeiro\Geral\Movimento\RnGenerico\uTMov_FinanceiroMovBancario.pas',
  uTCad_Cheque in '..\..\..\..\RepTmp\Financeiro\Geral\Cadastro\RnGenerico\uTCad_Cheque.pas',
  ifOtr_EMail in '..\..\..\..\RepTmp\Geral\Geral\Outro\InterfaceGenerico\ifOtr_EMail.pas' {fOtr_EMail},
  uTOtr_ContaBoletoRetornoLog in '..\..\..\..\RepTmp\Financeiro\ContaReceber\Outros\RnGenerico\uTOtr_ContaBoletoRetornoLog.pas',
  mDMRel_SatLayoutCupomFiscal in '..\..\..\..\RepTmp\Fiscal\SAT\Relatorio\RnGenerico\mDMRel_SatLayoutCupomFiscal.pas' {DMRel_SatLayoutCupomFiscal: TDataModule},
  uTCns_Parametro in '..\..\..\..\RepTmp\Geral\Geral\Consulta\RnGenerico\uTCns_Parametro.pas',
  ifCad_SpedReceitaBrutaMensal in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\InterfaceGenerico\ifCad_SpedReceitaBrutaMensal.pas' {fCad_SpedReceitaBrutaMensal},
//  uTCad_SpedReceitaBrutaMensal in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\uTCad_SpedReceitaBrutaMensal.pas',
//  uTCns_SpedReceitaBrutaMensal in '..\..\..\..\RepTmp\Fiscal\Geral\Consulta\RNGenerico\uTCns_SpedReceitaBrutaMensal.pas',
  ifCad_SpedApuracaoIPI in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\InterfaceGenerico\ifCad_SpedApuracaoIPI.pas' {fCad_SpedApuracaoIPI},
//  uTCad_SpedApuracaoIPI in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\uTCad_SpedApuracaoIPI.pas',
//  uTCns_SpedApuracaoIPI in '..\..\..\..\RepTmp\Fiscal\Geral\Consulta\RNGenerico\uTCns_SpedApuracaoIPI.pas',
  ifCad_SpedApuracaoICMS in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\InterfaceGenerico\ifCad_SpedApuracaoICMS.pas' {fCad_SpedApuracaoICMS},
//  uTCns_SpedApuracaoICMS in '..\..\..\..\RepTmp\Fiscal\Geral\Consulta\RNGenerico\uTCns_SpedApuracaoICMS.pas',
//  uTCad_SpedApuracaoICMS in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\uTCad_SpedApuracaoICMS.pas',
//  uTCad_SpedApuracaoICMSItem in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\uTCad_SpedApuracaoICMSItem.pas',
  uTCad_SpedApuracaoICMSItemSPED110 in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\uTCad_SpedApuracaoICMSItemSPED110.pas',
  uTCad_SpedApuracaoICMSItemSPED210 in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\uTCad_SpedApuracaoICMSItemSPED210.pas',
  ifCad_SpedApuracaoICMSST in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\InterfaceGenerico\ifCad_SpedApuracaoICMSST.pas' {fCad_SpedApuracaoICMSST},
  uTCad_SpedApuracaoICMSST in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\uTCad_SpedApuracaoICMSST.pas',
  uTCns_SpedApuracaoICMSST in '..\..\..\..\RepTmp\Fiscal\Geral\Consulta\RNGenerico\uTCns_SpedApuracaoICMSST.pas',
  uTOtr_SpedE210GeracaoAutomatica in '..\..\..\..\RepTmp\Fiscal\Geral\Outros\RnGenerico\uTOtr_SpedE210GeracaoAutomatica.pas',
  uTCad_SpedApuracaoICMSAjusteSped210 in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\uTCad_SpedApuracaoICMSAjusteSped210.pas',
  uTCad_SpedApuracaoICMSAjusteSped110 in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\uTCad_SpedApuracaoICMSAjusteSped110.pas',
  uTCad_SpedApuracaoICMSAjuste in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\uTCad_SpedApuracaoICMSAjuste.pas',
  uTCad_SpedApuracaoIPIItem in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\uTCad_SpedApuracaoIPIItem.pas',
  ifOtr_SintegraExp in '..\..\..\..\Repositorio\Outros\Sintegra\InterfaceGenerico\ifOtr_SintegraExp.pas' {fOtr_SintegraExp},
  uTOtr_Sintegra in '..\..\..\..\Repositorio\Outros\Sintegra\RnGenerico\uTOtr_Sintegra.pas',
  uTOtr_InventarioSintetico in '..\..\..\..\Repositorio\Movimento\Fiscal\Sintegra\RnGenerico\uTOtr_InventarioSintetico.pas',
  uTOtr_InventarioSinteticoAnual in '..\..\..\..\Repositorio\Movimento\Fiscal\Sintegra\RnGenerico\uTOtr_InventarioSinteticoAnual.pas',
  ifOtr_InventarioSinteticoAnual in '..\..\..\..\Repositorio\Movimento\Fiscal\Sintegra\InterfaceGenerico\ifOtr_InventarioSinteticoAnual.pas' {fOtr_InventarioSinteticoAnual},
  uTOtr_FiscalFechamento in '..\..\..\..\RepTmp\Fiscal\Geral\Outros\RnGenerico\uTOtr_FiscalFechamento.pas',
  ifOtr_SpedFiscal in '..\..\..\..\RepTmp\Fiscal\Geral\Outros\InterfaceGenerico\ifOtr_SpedFiscal.pas' {fOtr_SpedFiscal},
  ifExp_SpedPisCoFins in '..\..\..\..\RepTmp\Fiscal\Geral\Exportacao\InterfaceGenerico\ifExp_SpedPisCoFins.pas' {fExp_SpedPisCoFins},
  uTExp_FiscalSpedPisCofins in '..\..\..\..\RepTmp\Fiscal\Geral\Exportacao\RNGenerico\uTExp_FiscalSpedPisCofins.pas',
  uTOtr_SpedAtualizaPisCofins in '..\..\..\..\RepTmp\Fiscal\Geral\Outros\RnGenerico\uTOtr_SpedAtualizaPisCofins.pas',
  ifOtr_SpedAtualizaPisCofins in '..\..\..\..\RepTmp\Fiscal\Geral\Outros\InterfaceGenerico\ifOtr_SpedAtualizaPisCofins.pas' {fOtr_SpedAtualizaPisCofins},
  uTExp_FiscalSped in '..\..\..\..\RepTmp\Fiscal\Geral\Exportacao\RNGenerico\uTExp_FiscalSped.pas',
  uTOtr_SpedAtualiza in '..\..\..\..\RepTmp\Fiscal\Geral\Outros\RnGenerico\uTOtr_SpedAtualiza.pas',
  ifOtr_SpedAtualiza in '..\..\..\..\RepTmp\Fiscal\Geral\Outros\InterfaceGenerico\ifOtr_SpedAtualiza.pas' {fOtr_SpedAtualiza},
  ifOtr_ContaParcelaNossoNumero in '..\..\..\..\RepTmp\Financeiro\ContaPagar\Outros\InterfaceGenerico\ifOtr_ContaParcelaNossoNumero.pas' {fOtr_ContaParcelaNossoNumero},
  ifOtr_GerarRegistroC112SPED in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Outro\InterfaceGenerico\ifOtr_GerarRegistroC112SPED.pas' {fOtr_GerarRegistroC112SPED},
  uTCns_SpedRegistroC112 in '..\..\..\..\RepTmp\Fiscal\Geral\Consulta\RNGenerico\uTCns_SpedRegistroC112.pas',
  uTCad_SpedRegistroC112 in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\uTCad_SpedRegistroC112.pas',
  uTCad_SpedRegistroC112Item in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\uTCad_SpedRegistroC112Item.pas',
  uTOtr_GerarRegistroC112SPED in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Outro\RNGenerico\uTOtr_GerarRegistroC112SPED.pas',
  uTCad_ContaCorrente in '..\..\..\..\RepTmp\Financeiro\Geral\Cadastro\RnGenerico\uTCad_ContaCorrente.pas',
  uTCfg_XMLconfiguracao in '..\..\..\..\RepTmp\Geral\Geral\Configuracao\RNGenerico\uTCfg_XMLconfiguracao.pas',
  uTOtr_SATXmlToNotaFiscalSAT in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Outro\RNGenerico\uTOtr_SATXmlToNotaFiscalSAT.pas',
  uTOtr_XmlToNotaFiscal in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Outro\RNGenerico\uTOtr_XmlToNotaFiscal.pas',
  uTOtr_SATXmlToNotaFiscal in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Outro\RNGenerico\uTOtr_SATXmlToNotaFiscal.pas',
  uTCad_CadastroTributoDiferenciado in '..\..\..\..\RepTmp\Geral\Cadastro\Cadastro\RnGenerico\uTCad_CadastroTributoDiferenciado.pas',
  uTCns_FCP_UF in '..\..\..\..\RepTmp\Fiscal\Geral\Consulta\RNGenerico\uTCns_FCP_UF.pas',
  ifCns_FCP in '..\..\..\..\RepTmp\Fiscal\Geral\Consulta\InterfaceGenerico\ifCns_FCP.pas' {fCns_FCP},
  uTMov_ContaTEF in '..\..\..\..\RepTmp\Financeiro\Conta\Movimento\RNGenerico\uTMov_ContaTEF.pas',
  uTOtr_ContaParcelaGerarCartao in '..\..\..\..\RepTmp\Financeiro\Conta\Outros\RNGenerico\uTOtr_ContaParcelaGerarCartao.pas',
  ifOtr_FiscalFechamento in '..\..\..\..\RepTmp\Fiscal\Geral\Outros\InterfaceGenerico\ifOtr_FiscalFechamento.pas' {fOtr_FiscalFechamento},
  uTCns_FiscalFechamento in '..\..\..\..\RepTmp\Fiscal\Geral\Consulta\RNGenerico\uTCns_FiscalFechamento.pas' {uTCns_FiscalFechamento},
  ifCad_CEST in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\InterfaceGenerico\ifCad_CEST.pas' {fCad_CEST},
  uTCns_CEST in '..\..\..\..\RepTmp\Fiscal\Geral\Consulta\RNGenerico\uTCns_CEST.pas',
  uTCad_CEST in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\uTCad_CEST.pas',
  uTCad_ClassificacaoFiscalCEST in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\uTCad_ClassificacaoFiscalCEST.pas',
  uTOtr_SysScriptLog in '..\..\..\..\RepTmp\Diverso\Util\Outros\RnGenerico\uTOtr_SysScriptLog.pas',
  ifCad_SpedApuracaoICMSDifal in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\InterfaceGenerico\ifCad_SpedApuracaoICMSDifal.pas' {fCad_SpedApuracaoICMSDifal},
  uTCns_SpedApuracaoICMSDifal in '..\..\..\..\RepTmp\Fiscal\Geral\Consulta\RNGenerico\uTCns_SpedApuracaoICMSDifal.pas',
  uTCad_SpedApuracaoICMSDifal in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\uTCad_SpedApuracaoICMSDifal.pas',
  uTCad_SpedApuracaoICMSAjusteSped310 in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\uTCad_SpedApuracaoICMSAjusteSped310.pas',
  uTCad_SpedApuracaoICMSItemSPED310 in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\uTCad_SpedApuracaoICMSItemSPED310.pas',
  uTCad_SpedApuracaoICMSAjusteDetalheSped310 in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\uTCad_SpedApuracaoICMSAjusteDetalheSped310.pas',
  uTOtr_SpedE310GeracaoAutomatica in '..\..\..\..\RepTmp\Fiscal\Geral\Outros\RnGenerico\uTOtr_SpedE310GeracaoAutomatica.pas',
  uTCad_CadastroVeiculo in '..\..\..\..\RepTmp\Geral\Cadastro\Cadastro\RnGenerico\uTCad_CadastroVeiculo.pas',
  uTCns_SitTributaria in '..\..\..\..\RepTmp\Geral\Geral\Consulta\RnGenerico\uTCns_SitTributaria.pas',
  ifMov_NotaFiscalAtualizaItens in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Movimento\InterfaceGenerico\ifMov_NotaFiscalAtualizaItens.pas' {fMov_NotaFiscalAtualizaItens},
  ifCfg_ParametroSPED in '..\..\..\..\RepTmp\Geral\Geral\Configuracao\InterfaceGenerico\ifCfg_ParametroSPED.pas' {fCfg_ParametroSPED},
  uTCad_ContaCorrenteBoleto in '..\..\..\..\RepTmp\Financeiro\Geral\Cadastro\RnGenerico\uTCad_ContaCorrenteBoleto.pas',
  ifCad_ContaCorrenteBoleto in '..\..\..\..\RepTmp\Financeiro\Geral\Cadastro\InterfaceGenerico\ifCad_ContaCorrenteBoleto.pas' {fCad_ContaCorrenteBoleto},
  uTCns_ContaCorrenteBoleto in '..\..\..\..\RepTmp\Financeiro\Geral\Consulta\RnGenerico\uTCns_ContaCorrenteBoleto.pas',
  uTOtr_GetNumeroDocumento in '..\..\..\..\RepTmp\Financeiro\Geral\Outros\RnGenerico\uTOtr_GetNumeroDocumento.pas',
  uTCad_CNABLote in '..\..\..\..\RepTmp\Financeiro\Geral\Cadastro\RnGenerico\uTCad_CNABLote.pas',
  uTCad_CNABLoteItem in '..\..\..\..\RepTmp\Financeiro\Geral\Cadastro\RnGenerico\uTCad_CNABLoteItem.pas',
  uTCns_ContaCorrenteConfigLoader in '..\..\..\..\RepTmp\Financeiro\Geral\Consulta\RnGenerico\uTCns_ContaCorrenteConfigLoader.pas',
  uTOtr_ContaCorrenteConfigDefault in '..\..\..\..\RepTmp\Financeiro\Geral\Outros\RnGenerico\uTOtr_ContaCorrenteConfigDefault.pas',
  Vcl.Themes,
  Vcl.Styles,
  uT_Modulos in '..\..\Comum\FuturaEFD\uT_Modulos.pas',
  iFOtr_SpedFiscalValidacao in '..\..\..\..\RepTmp\Fiscal\Geral\Outros\InterfaceGenerico\iFOtr_SpedFiscalValidacao.pas' {FOtr_SpedFiscalValidacao},
  uTOtr_SpedFiscalValidacao in '..\..\..\..\RepTmp\Fiscal\Geral\Outros\RnGenerico\uTOtr_SpedFiscalValidacao.pas',
  mDMRel_SpedFiscalValidacao in '..\..\..\..\RepTmp\Fiscal\Geral\Relatorio\RnGenerico\mDMRel_SpedFiscalValidacao.pas' {DataModule3: TDataModule},
  uTLyt_Cep in '..\..\..\..\RepTmp\Venda\Gourmet\Layout\RnGourmet\uTLyt_Cep.pas',
  ifCad_PlanoContaContabil in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\InterfaceGenerico\ifCad_PlanoContaContabil.pas' {fCad_PlanoContaContabil},
  uTCad_PlanoContaContabil in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\uTCad_PlanoContaContabil.pas',
  uTCns_PlanoContaContabil in '..\..\..\..\RepTmp\Fiscal\Geral\Consulta\RNGenerico\uTCns_PlanoContaContabil.pas',
  uT_CepGridManualDinamico in '..\..\..\..\RepTmp\Geral\Gourmet\Outro\RnGenerico\uT_CepGridManualDinamico.pas',
  uTCad_SpedApuracaoIPIE531 in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\uTCad_SpedApuracaoIPIE531.pas',
  uTOtr_NotaFiscalDivisao in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Outro\RNGenerico\uTOtr_NotaFiscalDivisao.pas',
  ifOtr_NfeManifestacaoDestinatarioConfirmacaoSemXML in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Outro\InterfaceGenerico\ifOtr_NfeManifestacaoDestinatarioConfirmacaoSemXML.pas' {fOtr_NfeManifestacaoDestinatarioConfirmacaoSemXML},
  ifOtr_NfeManifestacaoDestinatarioImg in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Outro\InterfaceGenerico\ifOtr_NfeManifestacaoDestinatarioImg.pas' {fOtr_NfeManifestacaoDestinatarioImg},
  uTOtr_PedidoProcessoControle in '..\..\..\..\RepTmp\Venda\Pedido\Outro\RnGenerico\uTOtr_PedidoProcessoControle.pas',
  uTMov_NotaFiscalPagamento in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Movimento\RnGenerico\uTMov_NotaFiscalPagamento.pas',
  uTCad_SpedApuracaoICMSItemSPED113 in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\uTCad_SpedApuracaoICMSItemSPED113.pas',
  uTCad_ProdutoCaixa in '..\..\..\..\RepTmp\Estoque\Produto\Cadastro\RNGenerico\uTCad_ProdutoCaixa.pas',
  ifOtr_TravaMinimoVenda in '..\..\..\..\RepTmp\Venda\Geral\Outro\RnGenerico\ifOtr_TravaMinimoVenda.pas' {fOtr_TravaMinimoVenda},
  ifOtr_TravaMinimoVendaList in '..\..\..\..\RepTmp\Venda\Geral\Outro\RnGenerico\ifOtr_TravaMinimoVendaList.pas' {FOtr_TravaMinimoVendaList},
  uTMov_NotaFiscalAvulsa in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Movimento\RnGenerico\uTMov_NotaFiscalAvulsa.pas',
  uTOtr_AcBrDANFERL in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Relatorio\RNGenerico\uTOtr_AcBrDANFERL.pas',
  uTOtr_ImpressaoFiscal in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Relatorio\RNGenerico\uTOtr_ImpressaoFiscal.pas',
  ifOtr_CadastroAviso in '..\..\..\..\RepTmp\Geral\Cadastro\Outro\InterfaceGenerico\ifOtr_CadastroAviso.pas' {fOtr_CadastroAviso},
  mDMRel_ListaEscolar in '..\..\..\..\RepTmp\Venda\Pedido\Relatorio\RNGenerico\mDMRel_ListaEscolar.pas' {DMRel_ListaEscolar: TDataModule},
  uTCns_InventarioSintetico in '..\..\..\..\RepTmp\Fiscal\Inventario\Consulta\RnGenerico\uTCns_InventarioSintetico.pas',
  uTCad_ProdutoConversao in '..\..\..\..\RepTmp\Estoque\Produto\Cadastro\RNGenerico\uTCad_ProdutoConversao.pas',
  ifCad_ProdutoConversao in '..\..\..\..\RepTmp\Estoque\Produto\Cadastro\InterfaceGenerico\ifCad_ProdutoConversao.pas' {fCad_ProdutoConversao},
  ifOtr_InventarioIncluirProduto in '..\..\..\..\Repositorio\Movimento\Fiscal\Sintegra\InterfaceGenerico\ifOtr_InventarioIncluirProduto.pas' {fOtr_InventarioIncluirProduto},
  uTOtr_NfeXmlToNotaFiscalCTE in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Outro\RNGenerico\uTOtr_NfeXmlToNotaFiscalCTE.pas',
  ifCad_FatorConversaoGrade in '..\..\..\..\RepTmp\Estoque\Produto\Cadastro\InterfaceGenerico\ifCad_FatorConversaoGrade.pas' {fCad_FatorConversaoGrade},
  uTCad_ProdutoGradeConversao in '..\..\..\..\RepTmp\Estoque\Produto\Cadastro\RNGenerico\uTCad_ProdutoGradeConversao.pas',
  uTOtr_ProdutoGradeItem in '..\..\..\..\RepTmp\Estoque\Produto\Outro\RNGenerico\uTOtr_ProdutoGradeItem.pas',
  uTOtr_ProdutoGradeItemFactory in '..\..\..\..\RepTmp\Estoque\Produto\Outro\RNGenerico\uTOtr_ProdutoGradeItemFactory.pas',
  uTCad_ProdutoGradeImagem in '..\..\..\..\RepTmp\Estoque\Produto\Cadastro\RNGenerico\uTCad_ProdutoGradeImagem.pas',
  uTCad_ProdutoGradeGuarnicao in '..\..\..\..\RepTmp\Estoque\Produto\Cadastro\RNGenerico\uTCad_ProdutoGradeGuarnicao.pas',
  uTCad_ProdutoGradeInfoAdicionais in '..\..\..\..\RepTmp\Estoque\Produto\Cadastro\RNGenerico\uTCad_ProdutoGradeInfoAdicionais.pas',
  uTCad_ProdutoGradeItem in '..\..\..\..\RepTmp\Estoque\Produto\Cadastro\RNGenerico\uTCad_ProdutoGradeItem.pas',
  uTCad_ProdutoGradeComissao in '..\..\..\..\RepTmp\Estoque\Produto\Cadastro\RNGenerico\uTCad_ProdutoGradeComissao.pas',
  uTOtr_ProdutoGradeItemDinamico in '..\..\..\..\RepTmp\Estoque\Produto\Outro\RNGenerico\uTOtr_ProdutoGradeItemDinamico.pas',
  uTOtr_ProdutoGradeItemCompleto in '..\..\..\..\RepTmp\Estoque\Produto\Outro\RNGenerico\uTOtr_ProdutoGradeItemCompleto.pas',
  uTCad_ProdutoGradeFornecedor in '..\..\..\..\RepTmp\Estoque\Produto\Cadastro\RNGenerico\uTCad_ProdutoGradeFornecedor.pas',
  uTCad_ProdutoGuarnicao in '..\..\..\..\RepTmp\Estoque\Produto\Cadastro\RNFuturaRestaurante\uTCad_ProdutoGuarnicao.pas',
  uTCad_ProdutoGradeDesconto in '..\..\..\..\RepTmp\Estoque\Produto\Cadastro\RNGenerico\uTCad_ProdutoGradeDesconto.pas',
  uTCad_ProdutoImagem in '..\..\..\..\RepTmp\Estoque\Produto\Cadastro\RNGenerico\uTCad_ProdutoImagem.pas',
  uTCad_ProdutoComissao in '..\..\..\..\RepTmp\Estoque\Produto\Cadastro\RNGenerico\uTCad_ProdutoComissao.pas',
  uTCad_ProdutoDescontoAutomatico in '..\..\..\..\RepTmp\Estoque\Produto\Cadastro\RNGenerico\uTCad_ProdutoDescontoAutomatico.pas',
  uTOtr_SysValoresAdicionais in '..\..\..\..\RepTmp\Geral\Cadastro\Outro\RnGenerico\uTOtr_SysValoresAdicionais.pas',
  uTCad_ProdutoInfoAdicionais in '..\..\..\..\RepTmp\Estoque\Produto\Cadastro\RNGenerico\uTCad_ProdutoInfoAdicionais.pas',
  uTCad_PedidoDesconto in '..\..\..\..\RepTmp\Venda\Geral\Cadastro\RnGenerico\uTCad_PedidoDesconto.pas',
  uTOtr_ProdutoConversaoPreco in '..\..\..\..\RepTmp\Estoque\Produto\Outro\RNGenerico\uTOtr_ProdutoConversaoPreco.pas',
  ifMov_NotaFiscalD100 in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Movimento\InterfaceGenerico\ifMov_NotaFiscalD100.pas' {fMov_NotaFiscalD100},
  uTCns_NotaFiscalD100 in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Consulta\RNGenerico\uTCns_NotaFiscalD100.pas',
  uT_SefazCfgIni in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Outro\RNGenerico\uT_SefazCfgIni.pas',
  uTOtr_MetodoPermanente_SQL in '..\..\..\..\RepTmp\Fiscal\Geral\Outros\RnGenerico\uTOtr_MetodoPermanente_SQL.pas',
  uTExp_MetodoPermanente in '..\..\..\..\RepTmp\Fiscal\Geral\Exportacao\RNGenerico\uTExp_MetodoPermanente.pas',
  ifExp_MetodoPermanente in '..\..\..\..\RepTmp\Fiscal\Geral\Exportacao\InterfaceGenerico\ifExp_MetodoPermanente.pas' {fExp_MetodoPermanente},
  uTCad_MetodoPermanenteSaldo in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\uTCad_MetodoPermanenteSaldo.pas',
  uTCad_MetodoPermanenteSaldoICMS in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\uTCad_MetodoPermanenteSaldoICMS.pas',
  uTOtr_ExcluiCaixaItem in '..\..\..\..\RepTmp\Venda\PDV\Outro\RnGenerico\uTOtr_ExcluiCaixaItem.pas',
  uTOtr_ChequeValidar in '..\..\..\..\RepTmp\Financeiro\Geral\Outros\RnGenerico\uTOtr_ChequeValidar.pas',
  uTOtr_LogPedidoPDV in '..\..\..\..\RepTmp\Venda\PDV\Outro\RnGenerico\uTOtr_LogPedidoPDV.pas',
  ifOtr_Confirmacao in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Outro\InterfaceGenerico\ifOtr_Confirmacao.pas',
  uTOtr_NotaExcluir in '..\..\..\..\RepTmp\Fiscal\NotaFiscal\Outro\RNGenerico\uTOtr_NotaExcluir.pas',
  uTOtr_ContaRegerarValor in '..\..\..\..\RepTmp\Financeiro\Conta\Outros\RNGenerico\uTOtr_ContaRegerarValor.pas',
  ifOtr_NfeXMLtoPedidoAtualiza in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Outro\InterfaceGenerico\ifOtr_NfeXMLtoPedidoAtualiza.pas' {fOtr_NfeXMLtoPedidoAtualiza},
  uTMov_CompraPedidoItem in '..\..\..\..\RepTmp\Compra\Pedido\Movimento\RNGenerico\uTMov_CompraPedidoItem.pas',
  ifCad_UnidadeSemelhante in '..\..\..\..\RepTmp\Estoque\Produto\Cadastro\InterfaceGenerico\ifCad_UnidadeSemelhante.pas' {fCad_UnidadeSemelhante},
  uTCad_Unidade in '..\..\..\..\RepTmp\Estoque\Geral\Cadastro\RNGenerico\uTCad_Unidade.pas',
  ifOtr_ClientePreCadastroValida in '..\..\..\..\RepTmp\Geral\Cadastro\Outro\InterfaceGenerico\ifOtr_ClientePreCadastroValida.pas' {fOtr_ClientePreCadastroValida},
  uTOtr_ControleEmpresa in '..\..\..\..\RepTmp\Geral\Geral\Outro\RnGenerico\uTOtr_ControleEmpresa.pas',
  uTOtr_ControleEquipamento in '..\..\..\..\RepTmp\Geral\Geral\Outro\RnFuturaOs\uTOtr_ControleEquipamento.pas',
  uTCad_ClienteAutomotivo in '..\..\..\..\RepTmp\Geral\Cadastro\Cadastro\RNFuturaOs\uTCad_ClienteAutomotivo.pas',
  uTCad_CadastroEnderecoAutomotivo in '..\..\..\..\RepTmp\Geral\Cadastro\Cadastro\RNFuturaOs\uTCad_CadastroEnderecoAutomotivo.pas',
  uTCad_OsEquipamento in '..\..\..\..\RepTmp\Geral\Cadastro\Cadastro\RNFuturaOs\uTCad_OsEquipamento.pas',
  ifSel_GrupoVenda in '..\..\..\..\RepTmp\Geral\Geral\Selecao\InterfaceGenerico\ifSel_GrupoVenda.pas' {fSel_GrupoVenda},
  uTSel_GrupoVenda in '..\..\..\..\RepTmp\Geral\Geral\Selecao\RnGenerico\uTSel_GrupoVenda.pas',
  uTCad_GrupoVenda in '..\..\..\..\RepTmp\Geral\Geral\Cadastro\RnGenerico\uTCad_GrupoVenda.pas',
  uTCad_GrupoVendaItem in '..\..\..\..\RepTmp\Geral\Geral\Cadastro\RnGenerico\uTCad_GrupoVendaItem.pas',
  uTOtr_ProdutoConversaoEstoque in '..\..\..\..\RepTmp\Estoque\Produto\Outro\RNGenerico\uTOtr_ProdutoConversaoEstoque.pas',
  ifOtr_NfeTerceiros_SetCfopFaltando in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Outro\InterfaceGenerico\ifOtr_NfeTerceiros_SetCfopFaltando.pas' {fOtr_NfeTerceiros_SetCfopFaltando},
  uTOtr_NfeTerceiros_SetCfopFaltando in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Outro\RNGenerico\uTOtr_NfeTerceiros_SetCfopFaltando.pas',
  uTOtr_ContaFlex in '..\..\..\..\RepTmp\Financeiro\Conta\Outros\RNGenerico\uTOtr_ContaFlex.pas',
  uTMov_ContaFlex in '..\..\..\..\RepTmp\Financeiro\Conta\Movimento\RNGenerico\uTMov_ContaFlex.pas',
  ifMov_Financeiro in '..\..\..\..\RepTmp\Financeiro\Geral\Movimento\InterfaceGenerico\ifMov_Financeiro.pas' {fMov_Financeiro},
  uTOtr_ExtratoFinanceiro in '..\..\..\..\RepTmp\Financeiro\Geral\Outros\RnGenerico\uTOtr_ExtratoFinanceiro.pas',
  ifMov_ExtratoFinanceiro in '..\..\..\..\RepTmp\Financeiro\Geral\Outros\InterFaceGenerico\ifMov_ExtratoFinanceiro.pas' {fMov_ExtratoFinanceiro},
  uTCns_FinanceiroMovBancario in '..\..\..\..\RepTmp\Financeiro\Geral\Consulta\RnGenerico\uTCns_FinanceiroMovBancario.pas',
  uTMov_FinanceiroCentroCusto in '..\..\..\..\RepTmp\Financeiro\Geral\Movimento\RnGenerico\uTMov_FinanceiroCentroCusto.pas',
  ifOtr_ParametroPesquisa in '..\..\..\..\RepTmp\Geral\Geral\Outro\InterfaceGenerico\ifOtr_ParametroPesquisa.pas' {fOtr_ParametroPesquisa},
  uTOtr_ParametroPesquisa in '..\..\..\..\RepTmp\Geral\Geral\Outro\RnGenerico\uTOtr_ParametroPesquisa.pas',
  uTOtr_ProdutoKitIncluirLista in '..\..\..\..\RepTmp\Venda\PDV\Outro\RnGenerico\uTOtr_ProdutoKitIncluirLista.pas',
  uTCad_ProdutoKit in '..\..\..\..\RepTmp\Estoque\Produto\Cadastro\RNGenerico\uTCad_ProdutoKit.pas',
  uTCad_ProdutoKitItem in '..\..\..\..\RepTmp\Estoque\Produto\Cadastro\RNGenerico\uTCad_ProdutoKitItem.pas',
  uTCad_ProdutoAcabado in '..\..\..\..\RepTmp\Estoque\Produto\Cadastro\RNGenerico\uTCad_ProdutoAcabado.pas',
  uTCad_PedidoDescontoItem in '..\..\..\..\RepTmp\Venda\Geral\Cadastro\RnGenerico\uTCad_PedidoDescontoItem.pas',
  ifMov_VendaPedidoItemBrinde in '..\..\..\..\RepTmp\Venda\Pedido\Movimento\InterfaceGenerico\ifMov_VendaPedidoItemBrinde.pas' {fMov_VendaPedidoItemBrinde},
  uTOtr_AcertoEstoque in '..\..\..\..\RepTmp\Geral\Pedido\Outro\RNGenerico\uTOtr_AcertoEstoque.pas',
  uTMov_AjusteEstoque in '..\..\..\..\RepTmp\Estoque\Pedido\Movimento\RnGenerico\uTMov_AjusteEstoque.pas',
  uTMov_AjusteEstoqueItem in '..\..\..\..\RepTmp\Estoque\Pedido\Movimento\RnGenerico\uTMov_AjusteEstoqueItem.pas',
  uTOtr_ProdutoGradeItemOutrasInfo in '..\..\..\..\RepTmp\Estoque\Produto\Outro\RNGenerico\uTOtr_ProdutoGradeItemOutrasInfo.pas',
  uTCad_ProdutoGradeVideo in '..\..\..\..\RepTmp\Estoque\Produto\Cadastro\RNGenerico\uTCad_ProdutoGradeVideo.pas',
  uTCad_ProdutoVideo in '..\..\..\..\RepTmp\Estoque\Produto\Cadastro\RNGenerico\uTCad_ProdutoVideo.pas',
  mDMRel_EtiquetaNotaFiscal in '..\..\..\..\RepTmp\Fiscal\Geral\Relatorio\RnGenerico\mDMRel_EtiquetaNotaFiscal.pas' {DMRel_EtiquetaNotaFiscal: TDataModule},
  uTOtr_EtiquetaNotaFiscal in '..\..\..\..\RepTmp\Fiscal\Geral\Outros\RnGenerico\uTOtr_EtiquetaNotaFiscal.pas',
  ifOtr_ValidaPermissaoSemEstoque in '..\..\..\..\RepTmp\Venda\Geral\Outro\InterfaceGenerico\ifOtr_ValidaPermissaoSemEstoque.pas' {fOtr_ValidaPermissaoSemEstoque},
  uTMov_FinanceiroCtaReceberBaixaSimples in '..\..\..\..\RepTmp\Financeiro\Geral\Movimento\RnGenerico\uTMov_FinanceiroCtaReceberBaixaSimples.pas',
  ifMov_MovimentoCartaoDadosPendente in '..\..\..\..\RepTmp\Venda\PDV\Movimento\InterfaceGenerico\ifMov_MovimentoCartaoDadosPendente.pas' {fMov_MovimentoCartaoDadosPendente},
  uTOtr_ThreadValidaClienteFutura in '..\..\..\..\RepTmp\Geral\Geral\Outro\RnGenerico\uTOtr_ThreadValidaClienteFutura.pas',
  uTOtr_NotaFiscalNFESendWhatsApp in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Outro\RNGenerico\uTOtr_NotaFiscalNFESendWhatsApp.pas',
  uTOtr_ImpressaoFiscalTerceiros in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Relatorio\RNGenerico\uTOtr_ImpressaoFiscalTerceiros.pas',
  ifCns_ReducaoICMSST in '..\..\..\..\RepTmp\Fiscal\Geral\Consulta\InterfaceGenerico\ifCns_ReducaoICMSST.pas' {fCns_ReducaoICMSST},
  uTCns_ReducaoICMSSTUF in '..\..\..\..\RepTmp\Fiscal\Geral\Consulta\RNGenerico\uTCns_ReducaoICMSSTUF.pas',
  uTCns_FaturaFutura in '..\..\..\..\RepTmp\Financeiro\ContaPagar\Consulta\RnGenerico\uTCns_FaturaFutura.pas',
  mDMRel_FaturaFutura in '..\..\..\..\RepTmp\Financeiro\ContaPagar\Relatorio\RnGenerico\mDMRel_FaturaFutura.pas' {DMRel_FaturaFutura: TDataModule},
  ifRel_SpedPisCofins in '..\..\..\..\RepTmp\Fiscal\Geral\Relatorio\InterfaceCampineira\ifRel_SpedPisCofins.pas' {fRel_SpedPisCofins},
  mDMRel_SpedPisCofins in '..\..\..\..\RepTmp\Fiscal\Geral\Relatorio\RnCampineira\mDMRel_SpedPisCofins.pas' {DMRel_SpedPisCofins: TDataModule},
  ifExp_GIA in '..\..\..\..\RepTmp\Fiscal\Geral\Exportacao\InterfaceGenerico\ifExp_GIA.pas' {fExp_GIA},
  uTExp_GIA in '..\..\..\..\RepTmp\Fiscal\Geral\Exportacao\RNGenerico\uTExp_GIA.pas',
  uTOtr_GIA in '..\..\..\..\RepTmp\Fiscal\Geral\Outros\RnGenerico\uTOtr_GIA.pas',
  uTOtr_WebServiceFiscalIni in '..\..\..\..\RepTmp\Fiscal\Geral\Outros\RnGenerico\uTOtr_WebServiceFiscalIni.pas',
  uT_LayoutEmailUtils in '..\..\..\..\RepTmp\Geral\Cadastro\Outro\RnGenerico\uT_LayoutEmailUtils.pas',
  uTOtr_LayoutEmail in '..\..\..\..\RepTmp\Geral\Cadastro\Outro\RnGenerico\uTOtr_LayoutEmail.pas',
  uTMov_CompraDevolucao in '..\..\..\..\RepTmp\Compra\Pedido\Movimento\RNGenerico\uTMov_CompraDevolucao.pas',
  uTOtr_CreditoUtils in '..\..\..\..\RepTmp\Financeiro\Conta\Outros\RNGenerico\uTOtr_CreditoUtils.pas',
  uTCad_CreditoCliente in '..\..\..\..\RepTmp\Geral\Cadastro\Cadastro\RnGenerico\uTCad_CreditoCliente.pas',
  iFrm_ProgressBar in '..\..\..\..\RepTmp\Diverso\Util\Outros\InterfaceGenerico\iFrm_ProgressBar.pas' {Frm_ProgressBar: TFrame},
  ifOtr_InventarioSaldoInicialImportaExporta in '..\..\..\..\RepTmp\Fiscal\Inventario\Cadastro\InterfaceGenerico\ifOtr_InventarioSaldoInicialImportaExporta.pas' {fOtr_InventarioSaldoInicialImportaExporta},
  uTOtr_DfeSetCfgACBr in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Outro\RNGenerico\uTOtr_DfeSetCfgACBr.pas',
  uTOtr_ListaCasamentoVinculo in '..\..\..\..\RepTmp\Venda\Pedido\Outro\RnGenerico\uTOtr_ListaCasamentoVinculo.pas',
  uTOtr_ListaCasamento in '..\..\..\..\RepTmp\Venda\Pedido\Outro\RnGenerico\uTOtr_ListaCasamento.pas',
  uTOtr_ListaCasamentoItem in '..\..\..\..\RepTmp\Venda\Pedido\Outro\RnGenerico\uTOtr_ListaCasamentoItem.pas',
  uTOtr_ListaVenda in '..\..\..\..\RepTmp\Venda\Pedido\Outro\RnGenerico\uTOtr_ListaVenda.pas',
  uTOtr_ListaVendaItem in '..\..\..\..\RepTmp\Venda\Pedido\Outro\RnGenerico\uTOtr_ListaVendaItem.pas',
  utOtr_GTINTipos in '..\..\..\..\RepTmp\Estoque\Produto\Outro\RNGenerico\utOtr_GTINTipos.pas',
  uTOtr_GTINVerificador in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Outro\RNGenerico\uTOtr_GTINVerificador.pas',
  uTOtr_GTINVerificadorAcbr in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Outro\RNGenerico\uTOtr_GTINVerificadorAcbr.pas',
  uTOtr_GtinProdutoValidador in '..\..\..\..\RepTmp\Estoque\Produto\Outro\RNGenerico\uTOtr_GtinProdutoValidador.pas',
  uTOtr_GTINVerificadorGS1 in '..\..\..\..\RepTmp\Fiscal\NotaFiscalEletronica\Outro\RNGenerico\uTOtr_GTINVerificadorGS1.pas',
  ifOtr_BancosBoleto in '..\..\..\..\RepTmp\Financeiro\Geral\Outros\InterFaceGenerico\ifOtr_BancosBoleto.pas' {fOtr_BancosBoleto},
  uTCad_CreditoFornecedor in '..\..\..\..\RepTmp\Geral\Cadastro\Cadastro\RnGenerico\uTCad_CreditoFornecedor.pas',
  uTCad_Credito in '..\..\..\..\RepTmp\Geral\Cadastro\Cadastro\RnGenerico\uTCad_Credito.pas',
  uTCad_CNABWs in '..\..\..\..\RepTmp\Financeiro\Geral\Cadastro\RnGenerico\uTCad_CNABWs.pas',
  uTCad_CNABWsLog in '..\..\..\..\RepTmp\Financeiro\Geral\Cadastro\RnGenerico\uTCad_CNABWsLog.pas',
  uTOtr_ImpressaoBoletoDinamico in '..\..\..\..\RepTmp\Geral\Geral\Outro\RnGenerico\uTOtr_ImpressaoBoletoDinamico.pas',
  uTSel_ContaBoletoInstrucao in '..\..\..\..\RepTmp\Financeiro\ContaReceber\Selecao\RnGenerico\uTSel_ContaBoletoInstrucao.pas',
  ifOtr_ContaBoletoInstrucao in '..\..\..\..\RepTmp\Financeiro\ContaReceber\Outros\InterfaceGenerico\ifOtr_ContaBoletoInstrucao.pas' {fOtr_ContaBoletoInstrucao},
  uTCad_CNABLoteAlteracao in '..\..\..\..\RepTmp\Financeiro\Geral\Cadastro\RnGenerico\uTCad_CNABLoteAlteracao.pas',
  uTOtr_CompraSugestao in '..\..\..\..\RepTmp\Compra\Pedido\Outro\RNGenerico\uTOtr_CompraSugestao.pas',
  uTCns_HistoricoPagamentoVinculado in '..\..\..\..\RepTmp\Venda\Geral\Consulta\RnGenerico\uTCns_HistoricoPagamentoVinculado.pas',
  uTCns_ChequeTerceiro in '..\..\..\..\RepTmp\Financeiro\Geral\Consulta\RnGenerico\uTCns_ChequeTerceiro.pas',
  uT_Login,
  ifOtr_ProdutoFiscalCompra in '..\..\..\..\RepTmp\Estoque\Produto\Cadastro\InterfaceGenerico\ifOtr_ProdutoFiscalCompra.pas' {fOtr_ProdutoFiscalCompra},
  uTOtr_InventarioSaldoInicialCSV in '..\..\..\..\RepTmp\Fiscal\Inventario\Outros\RnGenerico\uTOtr_InventarioSaldoInicialCSV.pas',
  uTOtr_InventarioSaldoInicialExporta in '..\..\..\..\RepTmp\Fiscal\Inventario\Outros\RnGenerico\uTOtr_InventarioSaldoInicialExporta.pas',
  uTOtr_InventarioSaldoInicialImporta in '..\..\..\..\RepTmp\Fiscal\Inventario\Outros\RnGenerico\uTOtr_InventarioSaldoInicialImporta.pas',
  uTOtr_InventarioSaldoInicialTransfere in '..\..\..\..\RepTmp\Fiscal\Inventario\Cadastro\RNGenerico\uTOtr_InventarioSaldoInicialTransfere.pas',
  ifCad_CodigoBeneficio in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\InterfaceGenerico\ifCad_CodigoBeneficio.pas' {fCad_CodigoBeneficio},
  uTCad_CodigoBeneficio in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\uTCad_CodigoBeneficio.pas',
  uTCad_CodigoBeneficioGrade in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\RNGenerico\uTCad_CodigoBeneficioGrade.pas',
  ifCad_CodigoBeneficioSimples in '..\..\..\..\RepTmp\Fiscal\Geral\Cadastro\InterfaceGenerico\ifCad_CodigoBeneficioSimples.pas' {fCad_CodigoBeneficioSimples},

  uTOtr_MainControllerGenerica in '..\..\..\..\RepTmp\Geral\Geral\Outro\RnGenerico\uTOtr_MainControllerGenerica.pas',

  iFrm_PreVisualizarTema in '..\..\..\..\RepTmp\Geral\Geral\Outro\InterfaceGenerico\iFrm_PreVisualizarTema.pas' {Frm_PreVisualizarTema: TFrame},
  ifrm_BarraModularMainController in '..\..\..\..\RepTmp\Diverso\Util\Outros\InterfaceGenerico\ifrm_BarraModularMainController.pas' {frm_BarraModularMainController: TFrame},
  ifCfg_ImpressoraPadraoModal in '..\..\..\..\RepTmp\Diverso\Util\Configuracao\InterfaceGenerico\ifCfg_ImpressoraPadraoModal.pas' {fCfg_ImpressoraPadraoModal},
  ifOtr_PainelAviso in '..\..\..\..\RepTmp\Geral\Geral\Configuracao\InterfaceGenerico\ifOtr_PainelAviso.pas' {fOtr_PainelAviso},
  ifCfg_ConfiguracaoUsuario in '..\..\..\..\RepTmp\Geral\Geral\Configuracao\InterfaceGenerico\ifCfg_ConfiguracaoUsuario.pas' {fCfg_ConfiguracaoUsuario},
  uTCad_Funcionario in '..\..\..\..\RepTmp\Geral\Cadastro\Cadastro\RNGenerico\uTCad_Funcionario.pas',
  uTCad_CadastroFuncionario in '..\..\..\..\RepTmp\Geral\Cadastro\Cadastro\RnGenerico\uTCad_CadastroFuncionario.pas',
  uTCad_Email in '..\..\..\..\RepTmp\Geral\Geral\Cadastro\RnGenerico\uTCad_Email.pas',
  uTCad_FuncionarioREP in '..\..\..\..\RepTmp\Geral\Cadastro\Cadastro\RnPonto\uTCad_FuncionarioREP.pas',
  uTSel_REPFuncionarios in '..\..\..\..\RepTmp\Diverso\REP\Selecao\RnGenerico\uTSel_REPFuncionarios.pas',
  uTCns_REP in '..\..\..\..\RepTmp\Diverso\REP\Consulta\RnGenerico\uTCns_REP.pas',
  uTCns_REPBatida in '..\..\..\..\RepTmp\Diverso\REP\Consulta\RnGenerico\uTCns_REPBatida.pas',
  uTOtr_RepUtils in '..\..\..\..\RepTmp\Geral\Geral\Outro\RnGenerico\uTOtr_RepUtils.pas',
  uTCad_REPHorario in '..\..\..\..\RepTmp\Diverso\REP\Cadastro\RnGenerico\uTCad_REPHorario.pas',
  uTCad_REPHorarioDias in '..\..\..\..\RepTmp\Diverso\REP\Cadastro\RnGenerico\uTCad_REPHorarioDias.pas',
  uTCad_REPHorarioGrade in '..\..\..\..\RepTmp\Diverso\REP\Cadastro\RnGenerico\uTCad_REPHorarioGrade.pas',
  ifCad_REPNUsuarios in '..\..\..\..\RepTmp\Diverso\REP\Cadastro\InterfaceGenerico\ifCad_REPNUsuarios.pas' {fCad_REPNUsuarios},
  uTCad_REPUsuarios in '..\..\..\..\RepTmp\Diverso\REP\Cadastro\RnGenerico\uTCad_REPUsuarios.pas',
  uTCns_REPUsuarios in '..\..\..\..\RepTmp\Diverso\REP\Consulta\RnGenerico\uTCns_REPUsuarios.pas',
  uTOtr_REPUsuarios in '..\..\..\..\RepTmp\Diverso\REP\Outro\RnGenerico\uTOtr_REPUsuarios.pas',
  uTSel_REPUsuarios in '..\..\..\..\RepTmp\Diverso\REP\Selecao\RnGenerico\uTSel_REPUsuarios.pas',
  ifMov_REPNColeta in '..\..\..\..\RepTmp\Diverso\REP\Movimento\InterfaceGenerico\ifMov_REPNColeta.pas' {fMov_REPNColeta},
  uTCns_REPColeta in '..\..\..\..\RepTmp\Diverso\REP\Consulta\RnGenerico\uTCns_REPColeta.pas',
  uTOtr_REPColeta in '..\..\..\..\RepTmp\Diverso\REP\Outro\RnGenerico\uTOtr_REPColeta.pas',
  ifOtr_REPColetaMaisInfo in '..\..\..\..\RepTmp\Diverso\REP\Outro\InterfaceGenerico\ifOtr_REPColetaMaisInfo.pas' {fOtr_REPColetaMaisInfo},
  uTCns_RepApuracao in '..\..\..\..\RepTmp\Diverso\REP\Consulta\RnGenerico\uTCns_RepApuracao.pas',
  uTOtr_REPApuracao in '..\..\..\..\RepTmp\Diverso\REP\Outro\RnGenerico\uTOtr_REPApuracao.pas',
  uTCad_REPNApuracao in '..\..\..\..\RepTmp\Diverso\REP\Cadastro\RnGenerico\uTCad_REPNApuracao.pas',
  uTCad_REPNApuracaoFuncionario in '..\..\..\..\RepTmp\Diverso\REP\Cadastro\RnGenerico\uTCad_REPNApuracaoFuncionario.pas',
  uTCad_REPNApuracaoFuncionarioDia in '..\..\..\..\RepTmp\Diverso\REP\Cadastro\RnGenerico\uTCad_REPNApuracaoFuncionarioDia.pas',
  ifCad_REPApuracaoSimples in '..\..\..\..\RepTmp\Diverso\REP\Cadastro\InterfaceGenerico\ifCad_REPApuracaoSimples.pas' {fCad_REPApuracaoSimples},
  uTOtr_AtualizacaoApuracaoFuncionario in '..\..\..\..\RepTmp\Diverso\Util\Outros\RnGerenciadorInterno\uTOtr_AtualizacaoApuracaoFuncionario.pas',
  uTOtr_AtualizacaoMeuSistema in '..\..\..\..\RepTmp\Diverso\Util\Outros\RnPonto\uTOtr_AtualizacaoMeuSistema.pas',
  iFrm_AtualizacaoItem in '..\..\..\..\RepTmp\Diverso\Util\Outros\InterfaceGenerico\iFrm_AtualizacaoItem.pas' {Frm_AtualizacaoItem: TFrame},
  uTOtr_AtualizacaoItem in '..\..\..\..\RepTmp\Diverso\Util\Outros\RnGenerico\uTOtr_AtualizacaoItem.pas',
  ifOtr_AtualizacaoItemCores in '..\..\..\..\RepTmp\Diverso\Util\Outros\InterfaceGenerico\ifOtr_AtualizacaoItemCores.pas' {fOtr_AtualizacaoItemCores},
  uTOtr_AtualizacaoConfig in '..\..\..\..\RepTmp\Diverso\Util\Outros\RnGenerico\uTOtr_AtualizacaoConfig.pas',
  IfOtr_AtualizacaoUltimaColeta in '..\..\..\..\RepTmp\Diverso\Util\Outros\InterfaceEFD\IfOtr_AtualizacaoUltimaColeta.pas' {Frm_AtualizacaoUltimaColeta: TFrame},
  uTOtr_AtualizacaoItemUltimaColeta in '..\..\..\..\RepTmp\Diverso\Util\Outros\RnPonto\uTOtr_AtualizacaoItemUltimaColeta.pas' {uTOtr_AtualizacaoItemUltimaColeta: U},
  IfOtr_AtualizacaoSincroniaPendente in '..\..\..\..\RepTmp\Diverso\Util\Outros\InterfaceEFD\IfOtr_AtualizacaoSincroniaPendente.pas' {Frm_AtualizacaoSincroniaPendente: TFrame},
  uTOtr_AtualizacaoItemSincroniaPendente in '..\..\..\..\RepTmp\Diverso\Util\Outros\RnPonto\uTOtr_AtualizacaoItemSincroniaPendente.pas',

  uT_TestCaseBaseSistema in '..\FuturaServerTest\uT_TestCaseBaseSistema.pas',
  uT_TestCaseBasePesquisa in '..\FuturaServerTest\uT_TestCaseBasePesquisa.pas',
  DUnitTestRunnerFutura,
  uTOtr_LogPonto in '..\..\..\..\RepTmp\Diverso\REP\Outro\RnGenerico\uTOtr_LogPonto.pas',
  uTCad_ProdutoFiscalGrupo in '..\..\..\..\RepTmp\Estoque\Produto\Cadastro\RNGenerico\uTCad_ProdutoFiscalGrupo.pas',
  uT_ProdutoFactoryMethod in '..\FuturaServerTest\uT_ProdutoFactoryMethod.pas',
  uTCad_TabelaPreco in '..\..\..\..\RepTmp\Geral\Geral\Cadastro\RnGenerico\uTCad_TabelaPreco.pas';

{$R *.RES}

begin
  LoadCFGIni;
  ExecutaLogin(LgnBancoDadosDireto, GDadosGerais.LoginTipoIni);

  GSysCfg.Geral.CfgDefault.EmpresaId := TBaseDadosPadrao.BD.Getlookup('1', '1', 'CADASTRO', 'FIRST 1 ID', 'CHK_EMPRESA = ''S''');
  GDadosGerais.UsuarioAtual.ID       := TBaseDadosPadrao.BD.Getlookup('1', '1', 'SYS_USUARIO', 'FIRST 1 ID');
  GSysCfg.Geral.Venda.TabelaPrecoId  := TBaseDadosPadrao.BD.Getlookup('1', '1', 'TABELA_PRECO', 'FIRST 1 ID');
  GSysCfg.Geral.CfgDefault.ClienteId := TBaseDadosPadrao.BD.Getlookup('1', '1', 'CADASTRO', 'FIRST 1 ID', 'CHK_CLIENTE = ''S''');
  GSysCfg.Geral.Ponto.DiaFechamento  := 25;

  DUnitTestRunnerFutura.RunRegisteredTests;
end.
